twilio/twilio-oai-generator

PULL_REQUEST_TEMPLATE.md, examples/go/oai.yaml, examples/go/test/api_test.go, examples/go/test/unit_test.go, src/main/resources/twilio-go/api.mustache
=> fix: parameter names in the request

src/main/resources/twilio-go/api.mustache
Internal Reference: DI-1132
These changes allow for better formatting using gdoc. (example [here](https://github.com/twilio/twilio-go/tree/godocs/localhost:8080/pkg/github.com/twilio))
=> update formatting for godoc generation

README.md, examples/build_twilio_go.py
Add instructions to generate terraform-provider-twilio from twilio-oai
=> docs: add terraform provider generation instructions

Dockerfile, Makefile
Fixes TravisCI complaining about the go version.
=> fix: do the go stuff in Docker

src/main/java/com/twilio/oai/AbstractTwilioGoGenerator.java, src/main/java/com/twilio/oai/TwilioGoGenerator.java, src/main/java/com/twilio/oai/TwilioTerraformGenerator.java, src/main/resources/terraform-provider-twilio/api.mustache
- Add subaccount support for twilio-terraform-provider
- Bug fixes
Related PR: https://github.com/twilio/terraform-provider-twilio/pull/23
- [  ] I have added the necessary documentation about the functionality in the appropriate .md file
=> feat: add subaccount support for terraform provider

src/main/java/com/twilio/oai/TwilioTerraformGenerator.java
https://github.com/twilio/terraform-provider-twilio/pull/30
=> chore: preserve resource ordering

src/main/java/com/twilio/oai/PathUtils.java, src/main/java/com/twilio/oai/TwilioTerraformGenerator.java, src/main/resources/terraform-provider-twilio/api.mustache
https://github.com/twilio/terraform-provider-twilio/pull/29
=> fix: use the instance path to determine the sid_key for 'create' endpoints

src/main/java/com/twilio/oai/TwilioTerraformGenerator.java
=> chore: more refactoring

src/main/java/com/twilio/oai/TwilioTerraformGenerator.java, src/main/resources/terraform-provider-twilio/api.mustache
=> chore: even MOAR  refactoring

src/main/java/com/twilio/oai/TwilioTerraformGenerator.java
We assume all optional properties may also be computed in the backend. E.g., unique_name is typically optional but it will be populated if omitted.
https://github.com/twilio/terraform-provider-twilio/pull/36
=> fix: make optional params computed as well

src/main/java/com/twilio/oai/TwilioTerraformGenerator.java, src/main/resources/terraform-provider-twilio/api.mustache
Also moves non-CRUD resource removal. These changes are needed to simplify changes when working across CRUD operations of a resource.
https://github.com/twilio/terraform-provider-twilio/pull/37
=> chore: refactor the resource ID lookup

src/main/java/com/twilio/oai/TwilioTerraformGenerator.java
Results in no changes to the provider. This is pre-work for other changes.
=> chore: refactor building of schema types

src/main/java/com/twilio/oai/AbstractTwilioGoGenerator.java, src/main/java/com/twilio/oai/TwilioGoGenerator.java, src/main/java/com/twilio/oai/TwilioTerraformGenerator.java, src/main/resources/terraform-provider-twilio/api.mustache, src/main/resources/twilio-go/api.mustache
https://github.com/twilio/terraform-provider-twilio/pull/43
https://github.com/twilio/twilio-go/pull/85
=> fix: make required query params required

src/main/java/com/twilio/oai/TwilioTerraformGenerator.java, src/main/resources/terraform-provider-twilio/README.mustache, src/main/resources/terraform-provider-twilio/api.mustache
https://github.com/twilio/terraform-provider-twilio/pull/46
=> docs: add resource docs for the terraform provider

src/main/java/com/twilio/oai/TwilioTerraformGenerator.java, src/main/resources/terraform-provider-twilio/api.mustache
https://github.com/twilio/terraform-provider-twilio/pull/48
=> feat: add resource importing

Dockerfile, examples/go/oai.yaml, examples/go/test/api_test.go, examples/go/test/unit_test.go, src/main/java/com/twilio/oai/PathUtils.java, src/main/java/com/twilio/oai/TwilioGoGenerator.java, src/main/java/com/twilio/oai/TwilioNodeGenerator.java, src/main/java/com/twilio/oai/TwilioTerraformGenerator.java, src/main/resources/twilio-go/README.mustache, src/main/resources/twilio-go/api.mustache, src/main/resources/twilio-go/api_service.mustache
https://github.com/twilio/twilio-go/pull/88
=> chore: split resources into separate files

README.md, examples/go/integration/api_test.go, examples/go/test_client.go, examples/go/unit/mock_client.go, examples/go/unit/unit_test.go, examples/oai.yaml, prism.sh
Removes all the untested oai.yaml parts, allows unit tests to be run separately, and updates assertions to have expected values first.
=> test: refactor unit and integration tests

src/main/java/com/twilio/oai/TwilioTerraformGenerator.java, src/main/resources/terraform-provider-twilio/api.mustache
https://github.com/twilio/terraform-provider-twilio/pull/59
=> fix: convert ints in path params to properly be imported

examples/terraform/client/provider.go, examples/terraform/unit/accounts_calls_recordings_test.go, examples/terraform/unit/credentials_aws_test.go, examples/terraform/unit/mock_client.go, src/main/java/com/twilio/oai/TwilioGoGenerator.java
Shorten the model names in twilio-go
Related PR: https://github.com/twilio/twilio-go/pull/108
=>  chore: refine generated go model names

src/main/resources/twilio-go/api.mustache
fix pagination logic with absolute urls
Related PR: https://github.com/twilio/twilio-go/pull/110
=> fix: twilio-go pagination

src/main/resources/twilio-go/api.mustache
fix typo
Related PR: https://github.com/twilio/twilio-go/pull/115
=> fix: page func in go

examples/terraform/client/provider.go, examples/terraform/unit/mock_client.go, examples/terraform/unit/resources_test.go, examples/terraform/unit/serverless_services_environments_test.go, examples/twilio_api_v2010.yaml, src/main/java/com/twilio/oai/TwilioTerraformGenerator.java, src/main/resources/terraform-provider-twilio/api.mustache
Related PR: https://github.com/twilio/terraform-provider-twilio/pull/68
=> fix: do not ignore resources with crd operations

pom.xml
=> chore: maven-compiler-plugin 3.9.0

pom.xml
=> chore: junit 4.13.2

src/main/java/com/twilio/oai/TwilioGoGenerator.java, src/main/resources/twilio-go/api.mustache, src/main/resources/twilio-go/api_doc.mustache
Partial fix for https://github.com/twilio/twilio-go/issues/146
Relates to https://github.com/twilio/twilio-go/pull/147
=> docs: fix the 'List*' operation return type documentation

examples/build_twilio_go.py
Librarian clones dependent package to submodules, which causes the build to fail with `java-openapi` branch for oai-generator. Maintaining go nomenclature for now to succeed librarian builds. 
=> fix: Revert back to Golang nomenclature

src/main/java/com/twilio/oai/TwilioJavaGenerator.java, src/main/resources/twilio-java/api.mustache
Fixes: https://issues.corp.twilio.com/browse/DII-273
Testing the hash generation logic: 
Matches with the one generated in yoyodyne: 
The signatures however need to be changed to match the types in python, which is done as part of a different ticket:
=> Calculate serial version uid

src/main/java/com/twilio/oai/TwilioJavaGenerator.java
Closes: [DII-274](https://issues.corp.twilio.com/browse/DII-274)
Skip automated api test and doc generation. Overriding the functionality where they are [set](https://github.com/OpenAPITools/openapi-generator/blob/5.3.x/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java#L144)
=> chore:  Skip automated api test and doc generation

examples/java/unit-test/rest/TwilioRestTest.java
Closes: DII-268
Added the Pagination Unit tests for List api calls in Java generated code.
The added unit test would test the functionality of the List api, the pagination handled in the java and error use-case.
=> chore: Java generated code pagination test.

src/main/resources/twilio-java/api.mustache
Serial uid fix : Appedning L to the long number
=> Serial uid fix : Appedning L to the long number

examples/java/unit-test/rest/TwilioRestTest.java, src/main/java/com/twilio/oai/TwilioJavaGenerator.java, src/main/resources/twilio-java/api.mustache, src/main/resources/twilio-java/creator.mustache, src/main/resources/twilio-java/reader.mustache
For: https://issues.corp.twilio.com/browse/DII-270
Generated files after the fix: 
printing all the parameters to verify these changes: 
https://gist.github.com/sr010/a3890352cccfb3d17fb26013b57c9860
=> Build date range support

examples/sonar-project.properties, prism.sh
Pipeline was failed due to invalid java sonar properties. I have disabled java test to unblock go and terraform pipeline run. We will fix java sonar properties in separate story.
=> fix: Disable java test and exclude sonar java run

examples/build_twilio_go.py, examples/twilio_api_v2010.yaml, src/main/java/com/twilio/oai/AbstractTwilioGoGenerator.java
Relates to https://github.com/twilio/twilio-go/pull/154
=> [DI-2026] fix: support operations with no 2XX responses

java.Dockerfile
[java-test run](https://gist.github.com/shrutiburman/0f9bc4ea0bbbe0e4985b78dcee6840af)
Related [PR](https://github.com/twilio/twilio-java/pull/678)
=> chore: refactor dockerfile

examples/go-client/helper/rest/api/v2010/api_test.go, examples/go-client/helper/rest/api/v2010/credentials_aws.go, examples/go-client/terraform/resources/README.md, examples/go-client/terraform/resources/api_default.go, examples/java/rest/api/v2010/credential/AwsCreator.java, examples/twilio_api_v2010.yaml, prism.sh, src/main/java/com/twilio/oai/TwilioGoGenerator.java, src/main/resources/twilio-go/partial_serialization.mustache
https://swagger.io/docs/specification/data-models/data-types/#any
Relates to:
* https://github.com/twilio/twilio-oai/pull/54
* https://github.com/twilio/twilio-go/pull/155
=> [DI-2039] feat: support marshaling of "any" type parameters in Go

examples/go-client/terraform/resources/README.md, src/main/java/com/twilio/oai/TwilioTerraformGenerator.java, src/main/resources/terraform-provider-twilio/README.mustache
[DI-2036](https://issues.corp.twilio.com/browse/DI-2036)
Related PRs:
https://code.hq.twilio.com/twilio/librarian/pull/375
https://github.com/twilio/terraform-provider-twilio/pull/107
=> chore: Removing v2010 prefix for terraform

examples/go-client/terraform/client/provider.go, examples/go-client/terraform/resources/api_default.go, examples/go-client/terraform/resources/api_test.go, src/main/java/com/twilio/oai/TwilioTerraformGenerator.java
[DI-2036](https://issues.corp.twilio.com/browse/DI-2036)
Changes: https://github.com/twilio/terraform-provider-twilio/pull/110
=> fix: Updating clientService to exclude prefix for v2010 api generation

examples/java/rest/api/v2010/AccountCreator.java, examples/java/rest/api/v2010/AccountDeleter.java, examples/java/rest/api/v2010/AccountFetcher.java, examples/java/rest/api/v2010/AccountReader.java, examples/java/rest/api/v2010/AccountUpdater.java, examples/java/rest/api/v2010/AwsCreator.java, examples/java/rest/api/v2010/AwsDeleter.java, examples/java/rest/api/v2010/AwsFetcher.java, examples/java/rest/api/v2010/AwsReader.java, examples/java/rest/api/v2010/AwsUpdater.java, examples/java/rest/api/v2010/CallCreator.java, examples/java/rest/api/v2010/CallDeleter.java, examples/java/rest/api/v2010/CallFetcher.java, examples/java/rest/api/v2010/call/FeedbackCallSummaryCreator.java, examples/java/unit-test/rest/TwilioRestTest.java, src/main/java/com/twilio/oai/TwilioJavaGenerator.java, src/main/resources/twilio-java/creator.mustache, src/main/resources/twilio-java/dateQueryParams.mustache, src/main/resources/twilio-java/dateTimeGroupParams.mustache, src/main/resources/twilio-java/deleter.mustache, src/main/resources/twilio-java/fetcher.mustache, src/main/resources/twilio-java/prefixedCollapsibleMapQParams.mustache, src/main/resources/twilio-java/queryParams.mustache, src/main/resources/twilio-java/reader.mustache, src/main/resources/twilio-java/updater.mustache
Closes DII 396 Support Query Parameters
Add new function 'addQueryParams' to add query parameters to the request from generated java libraries. This PR included test case changes as well for the above change
=> feat: Add addQueryParams function to generated java library

examples/build_twilio_library.py, examples/java/rest/api/v2010/Account.java, examples/java/rest/api/v2010/Aws.java, examples/java/rest/api/v2010/Call.java, examples/java/rest/api/v2010/call/FeedbackCallSummary.java, examples/scripts/clean_java_imports.py, examples/sonar-project.properties, src/main/java/com/twilio/oai/TwilioJavaGenerator.java, src/main/resources/twilio-java/api.mustache
Add python script to remove unused imports after java language code generation in build script.
=> chore: Remove unused imports

examples/java/unit-test/rest/TwilioRestTest.java, examples/sonar-project.properties
=> Improves unit test coverage

examples/java/unit-test/rest/TwilioRestTest.java
=> Increase java code coverage

examples/java/src/main/java/com/twilio/rest/api/v2010/AccountCreator.java, examples/java/src/main/java/com/twilio/rest/api/v2010/AccountDeleter.java, examples/java/src/main/java/com/twilio/rest/api/v2010/AccountFetcher.java, examples/java/src/main/java/com/twilio/rest/api/v2010/AccountUpdater.java, examples/java/src/main/java/com/twilio/rest/api/v2010/account/CallCreator.java, examples/java/src/main/java/com/twilio/rest/api/v2010/account/CallDeleter.java, examples/java/src/main/java/com/twilio/rest/api/v2010/account/CallFetcher.java, examples/java/src/main/java/com/twilio/rest/api/v2010/account/call/FeedbackCallSummaryCreator.java, examples/java/src/main/java/com/twilio/rest/api/v2010/credential/AwsDeleter.java, examples/java/src/main/java/com/twilio/rest/api/v2010/credential/AwsFetcher.java, examples/java/src/main/java/com/twilio/rest/api/v2010/credential/AwsUpdater.java, examples/java/src/main/java/com/twilio/rest/api/v2010/credential/NewCredentialsCreator.java, src/main/java/com/twilio/oai/TwilioJavaGenerator.java, src/main/resources/twilio-java/generate_uri.mustache
refactored java code for getting class name from vendor extensions 
=> fix: refactored code for java

scripts/build_twilio_library.py
Current logic for evaluating domain (folder package name) relies upon the spec file name, but this logic does not work for some spec files like https://github.com/twilio/twilio-oai/blob/main/spec/json/twilio_flex_v1.json here after evaluation domain name (flex) is different from expected domain name (flexapi) specified inside the spec file under url https://github.com/twilio/twilio-oai/blob/main/spec/json/twilio_flex_v1.json#L2578. 
Added logic for java to parse spec file and evaluate the domain folder name.
=> fix: updated domain folder name logic for java

examples/java/src/main/java/com/twilio/rest/api/v2010/AccountCreator.java, examples/java/src/main/java/com/twilio/rest/api/v2010/AccountDeleter.java, examples/java/src/main/java/com/twilio/rest/api/v2010/AccountFetcher.java, examples/java/src/main/java/com/twilio/rest/api/v2010/AccountReader.java, examples/java/src/main/java/com/twilio/rest/api/v2010/AccountUpdater.java, examples/java/src/main/java/com/twilio/rest/api/v2010/account/CallCreator.java, examples/java/src/main/java/com/twilio/rest/api/v2010/account/CallDeleter.java, examples/java/src/main/java/com/twilio/rest/api/v2010/account/CallFetcher.java, examples/java/src/main/java/com/twilio/rest/api/v2010/account/call/FeedbackCallSummaryCreator.java, examples/java/src/main/java/com/twilio/rest/api/v2010/credential/AwsDeleter.java, examples/java/src/main/java/com/twilio/rest/api/v2010/credential/AwsFetcher.java, examples/java/src/main/java/com/twilio/rest/api/v2010/credential/AwsReader.java, examples/java/src/main/java/com/twilio/rest/api/v2010/credential/AwsUpdater.java, examples/java/src/main/java/com/twilio/rest/api/v2010/credential/NewCredentialsCreator.java, examples/java/unit-test/rest/TwilioRestTest.java, src/main/java/com/twilio/oai/ConventionResolver.java, src/main/java/com/twilio/oai/TwilioJavaGenerator.java, src/main/resources/twilio-java/creator.mustache, src/main/resources/twilio-java/deleter.mustache, src/main/resources/twilio-java/fetcher.mustache, src/main/resources/twilio-java/postParams.mustache, src/main/resources/twilio-java/reader.mustache, src/main/resources/twilio-java/updater.mustache
Added support for map to json converter
=> fix: fixing cluster test issue

README.md, examples/go/Dockerfile
Jira:[ DI-2095](https://issues.corp.twilio.com/browse/DI-2095)
=> test: add datarace detection for go

examples/node/spec/unit/Accounts.spec.ts
=> test: add tests for node examples

src/main/java/com/twilio/oai/TwilioJavaGenerator.java
Modified code to process spec files in preview domain. Special processing added for preview domain as it doesnto have a version and files are organised under sub domains
=> feat: Enable preview domain handling sub domains instead of versions

src/main/java/com/twilio/oai/TwilioGoGenerator.java
Minor Fix to `postProcessModelProperty` and `processEnumParameters`
=> fix: Correctly set isEnum with dataFormat

scripts/build_twilio_library.py, src/main/java/com/twilio/oai/TwilioCsharpGenerator.java, src/main/resources/twilio-csharp/Options.mustache, src/main/resources/twilio-csharp/OptionsUsings.mustache, src/main/resources/twilio-csharp/Resource.mustache, src/main/resources/twilio-csharp/ResourceUsings.mustache
DII-471 Infra Setup for testing csharp - Part1
DII-459 Generate optimised imports for options and resource
Optimise the using statements used in Resource and Options files using the same logic from yoyodyne
=> feat: Generate optimised imports for options and resource

examples/node/lib/rest/api/v2010/accounts.ts, examples/node/lib/rest/api/v2010/accounts/calls.ts, examples/node/lib/rest/api/v2010/accounts/calls/feedbackSummary.ts, examples/node/lib/rest/api/v2010/credentials/aWS.ts, examples/node/spec/unit/Accounts.spec.ts, src/main/java/com/twilio/oai/TwilioNodeGenerator.java, src/main/resources/twilio-node/operation.mustache
- 'DateCreated<' and 'DateCreated>' from API spec now get converted to 'DateCreatedBefore' and DateCreatedAfter' in generated node code
- Modified operation.mustache file to make generated code specify the name of the 'params' argument in method calls. This allows for api requests to take in request queries (rather than just the body). 
- Existing test cases now verify all passed arguments
[Same fix for Java](https://github.com/twilio/twilio-oai-generator/pull/116)
=> fix: Build Node date range support

scripts/build_twilio_library.py
DII-471 Infra Setup for testing csharp - Part1
Changes in build_twilio_library script to generate csharp files to Rest folder instead of rest
=> fix: Changes in build_twilio_library script to generate csharp files to Rest folder instead of rest

src/main/java/com/twilio/oai/DirectoryStructureService.java, src/main/java/com/twilio/oai/TwilioCsharpGenerator.java
DII-456 Preview package and Generate Domains file
Enable files under preview domain for csharp library using open api generator
=> feat: Enable preview domain for csharp

scripts/build_twilio_library.py, src/main/java/com/twilio/oai/DirectoryStructureService.java, src/main/java/com/twilio/oai/TwilioCsharpGenerator.java, src/main/java/com/twilio/oai/common/CsharpResolver.java, src/main/java/com/twilio/oai/common/ReservedKeyword.java, src/main/resources/twilio-csharp/OptionsUsings.mustache, src/main/resources/twilio-csharp/ResourceUsings.mustache
=> Csharp bug fixes

src/main/resources/twilio-csharp/options/Params.mustache, src/main/resources/twilio-csharp/resource/ResponseModel.mustache
Remove setters from required variables in Resource file and option file.
=> feat: remove setters from required vars

examples/node/lib/rest/api/v2010/account.ts, examples/node/lib/rest/api/v2010/account/call.ts, examples/node/lib/rest/api/v2010/account/call/feedbackCallSummary.ts, examples/node/lib/rest/api/v2010/credential/aWS.ts, examples/node/lib/rest/api/v2010/credential/newCredentials.ts, src/main/java/com/twilio/oai/TwilioNodeGenerator.java
=> chore: update node HTTP method casing

src/main/java/com/twilio/oai/DirectoryStructureService.java, src/main/java/com/twilio/oai/EnumsResolver.java, src/main/java/com/twilio/oai/StringHelper.java, src/main/java/com/twilio/oai/TwilioCsharpGenerator.java, src/main/java/com/twilio/oai/common/CsharpResolver.java, src/main/resources/twilio-csharp/OptionsUsings.mustache, src/main/resources/twilio-csharp/ResourceUsings.mustache
[DII-617](https://issues.corp.twilio.com/browse/DII-617) BugFix: Required Import statements are not added when resource file has list of enum type variables
[DII-582](https://issues.corp.twilio.com/browse/DII-582) Add code changes to C# generator to handle domains without version in general
Handle import statement when enums of enum lists are part of resource and options files. Add code changes to C# generator to handle domains without version in general
=> fix: Handle import statement when enums of enum lists are part of resource and options files

.github/workflows/test.yml, Makefile, examples/csharp/Dockerfile, scripts/prism.sh
[DII-640](https://issues.corp.twilio.com/browse/DII-640) Setup Mono repo for twilio-oai-generator (examples folder)
Configuration changes to setup monorepo for csharp
=> feat: Configuration changes to setup monorepo for csharp

scripts/build_twilio_library.py
Removing domain name processing in build_twilio_library script for json. spec files as this is already handled in generators
[DII-649](https://issues.corp.twilio.com/browse/DII-649) Evaluate correct domain name with -api in name for yaml spec
Removing domain name processing in build_twilio_library script for json. spec files as this is already handled in generators
=> Removing domain name processing in build_twilio_library script for json

src/main/java/com/twilio/oai/TwilioCodegenAdapter.java, src/main/java/com/twilio/oai/common/ApplicationConstants.java, src/main/java/com/twilio/oai/resolver/csharp/CodegenParameterResolver.java
https://github.com/twilio/twilio-java/pull/717
=> fix: update reserved words

examples/node/lib/rest/flexApi/V1.ts, examples/node/lib/rest/flexApi/v1/credential.ts, examples/node/spec/unit/call.spec.ts, examples/node/spec/unit/credential.spec.ts, examples/spec/twilio_api_v2010.yaml, examples/spec/twilio_flex_v1.yaml, src/main/java/com/twilio/oai/DirectoryStructureService.java, src/main/java/com/twilio/oai/Inflector.java, src/main/java/com/twilio/oai/TwilioNodeGenerator.java, src/main/java/com/twilio/oai/resource/IResourceTree.java, src/main/java/com/twilio/oai/resource/Resource.java, src/main/java/com/twilio/oai/resource/ResourceMap.java, src/test/java/com/twilio/oai/InflectorTest.java
mountName required for fluent-style languages. Also fixes redundancies/bugs in the inflector.
=> feat: add support for mountName

examples/csharp/src/Twilio/Rest/Api/V2010/Account/Call/FeedbackCallSummaryResource.cs, examples/go/go-client/helper/rest/api/v2010/README.md, examples/go/go-client/helper/rest/api/v2010/accounts_calls_feedback_summary.go, examples/java/src/main/java/com/twilio/rest/api/v2010/account/call/FeedbackCallSummaryUpdater.java, examples/node/lib/rest/api/v2010/account/call/feedbackCallSummary.ts, examples/node/spec/unit/account/call.spec.ts, examples/spec/twilio_api_v2010.yaml, src/main/java/com/twilio/oai/resource/ResourceMap.java
Also updated test fixture endpoint to illustrate change has no impact on generated code structure.
=> feat: support dependent resources with additional sub-dirs

examples/java/src/main/java/com/twilio/rest/api/v2010/Account.java, examples/java/src/main/java/com/twilio/rest/api/v2010/AccountDeleter.java, examples/java/src/main/java/com/twilio/rest/api/v2010/AccountFetcher.java, examples/java/src/main/java/com/twilio/rest/api/v2010/AccountUpdater.java, examples/java/src/main/java/com/twilio/rest/api/v2010/account/Call.java, examples/java/src/main/java/com/twilio/rest/api/v2010/account/CallCreator.java, examples/java/src/main/java/com/twilio/rest/api/v2010/account/CallDeleter.java, examples/java/src/main/java/com/twilio/rest/api/v2010/account/CallFetcher.java, examples/java/src/main/java/com/twilio/rest/api/v2010/account/call/FeedbackCallSummary.java, examples/java/src/main/java/com/twilio/rest/api/v2010/account/call/FeedbackCallSummaryUpdater.java, examples/java/src/main/java/com/twilio/rest/flexapi/v1/Call.java, examples/java/src/main/java/com/twilio/rest/flexapi/v1/CallUpdater.java, examples/java/src/main/java/com/twilio/rest/flexapi/v1/credential/Aws.java, examples/java/src/main/java/com/twilio/rest/flexapi/v1/credential/AwsDeleter.java, examples/java/src/main/java/com/twilio/rest/flexapi/v1/credential/AwsFetcher.java, examples/java/src/main/java/com/twilio/rest/flexapi/v1/credential/AwsUpdater.java, examples/java/src/main/java/com/twilio/rest/versionless/deployedDevices/Fleet.java, examples/java/src/main/java/com/twilio/rest/versionless/deployedDevices/FleetFetcher.java, src/main/java/com/twilio/oai/TwilioJavaGenerator.java, src/main/resources/twilio-java/generate_uri.mustache, src/main/resources/twilio-java/reader.mustache
- path parameters field in java classes must have path string prefix as it was in java 8x. In java 9x we missed this which caused contradiction with properties fields with same name. 
=> fix: Add path prefix string to path parameters

examples/csharp/src/Twilio/Rest/Api/V2010/Account/Call/FeedbackCallSummaryResource.cs, examples/csharp/src/Twilio/Rest/Api/V2010/Account/CallResource.cs, examples/csharp/src/Twilio/Rest/Api/V2010/AccountResource.cs, examples/csharp/unit-test/Rest/TwilioRestTest.cs, src/main/resources/twilio-csharp/resource/Enum.mustache, src/main/resources/twilio-csharp/resource/ResponseModel.mustache
Fixed serialization issue of Resource Objects in csharp. Currently serialization of array of enums
gives a string instead of valid list of string representing the enums. This issue has been fixed
=> reposition json converter for enums

examples/node/lib/rest/api/v2010/account.ts, examples/node/lib/rest/api/v2010/account/call.ts, examples/node/lib/rest/api/v2010/account/call/feedbackCallSummary.ts, examples/node/lib/rest/flexApi/v1/call.ts, examples/node/lib/rest/flexApi/v1/credential.ts, examples/node/lib/rest/flexApi/v1/credential/aws.ts, examples/node/lib/rest/flexApi/v1/credential/newCredentials.ts, examples/node/lib/rest/versionless/deployed_devices/fleet.ts, examples/node/lib/rest/versionless/understand/assistant.ts, examples/node/spec/integration/apiIntegration.spec.ts, examples/node/spec/unit/account.spec.ts, src/main/resources/twilio-node/api-single.mustache, src/main/resources/twilio-node/responseModel.mustache
Also adds any missing solution types.
=> fix: use proper solution types for node

examples/node/Dockerfile, examples/node/Dockerfile-prettier, examples/node/lib/rest/api/v2010/account.ts, examples/node/lib/rest/api/v2010/account/call.ts, examples/node/lib/rest/api/v2010/account/call/feedbackCallSummary.ts, examples/node/lib/rest/flexApi/v1/call.ts, examples/node/lib/rest/flexApi/v1/credential.ts, src/main/java/com/twilio/oai/PathUtils.java, src/main/java/com/twilio/oai/TwilioNodeGenerator.java
In case refactorings lead to processing resources in a different order, use a TreeMap to ensure sorting by key.
=> chore: sort string map values for simpler diffing

examples/prism/docker-compose.yml, scripts/prism.sh
Usage: `LIBRARIES="node java" make test-docker`
=> feat: supporting only testing certain libraries

examples/node/lib/rest/flexApi/v1/credential/aws/history.ts, examples/node/spec/unit/credential.spec.ts, src/main/java/com/twilio/oai/DirectoryStructureService.java, src/main/java/com/twilio/oai/PathUtils.java, src/main/java/com/twilio/oai/TwilioJavaGenerator.java, src/main/java/com/twilio/oai/TwilioNodeGenerator.java, src/main/java/com/twilio/oai/common/ApplicationConstants.java, src/main/java/com/twilio/oai/common/EnumConstants.java, src/main/java/com/twilio/oai/resource/Resource.java, src/main/resources/twilio-node/api-single.mustache
https://github.com/twilio/twilio-node/pull/814
=> fix: support nested instance resources using the pathType in node-oai

examples/node/lib/rest/flexApi/v1/credential/newCredentials.ts, examples/node/spec/unit/call.spec.ts, examples/node/spec/unit/credential.spec.ts, src/main/java/com/twilio/oai/TwilioNodeGenerator.java
https://github.com/twilio/twilio-node/pull/815
=> fix: serialize objects properly in node-oai

examples/csharp/src/Twilio/Rest/FlexApi/V1/Credential/NewCredentialsOptions.cs, examples/csharp/src/Twilio/Rest/FlexApi/V1/Credential/NewCredentialsResource.cs, examples/go/go-client/helper/rest/flex/v1/credentials_aws.go, examples/go/go-client/terraform/resources/flex/v1/README.md, examples/go/go-client/terraform/resources/flex/v1/api_default.go, examples/java/src/main/java/com/twilio/rest/flexapi/v1/credential/NewCredentialsCreator.java, examples/node/lib/rest/flexApi/v1/credential.ts, examples/node/lib/rest/flexApi/v1/credential/aws.ts, examples/node/lib/rest/flexApi/v1/credential/newCredentials.ts, examples/node/spec/unit/credential.spec.ts, examples/spec/twilio_flex_v1.yaml, src/main/java/com/twilio/oai/PathUtils.java, src/main/java/com/twilio/oai/StringHelper.java, src/main/java/com/twilio/oai/resource/Resource.java
https://github.com/twilio/twilio-node/pull/816
=> fix: update casing for some mounts and properties in node-oai

examples/csharp/src/Twilio/Rest/FlexApi/V1/Credential/Aws/HistoryOptions.cs, examples/csharp/src/Twilio/Rest/FlexApi/V1/Credential/Aws/HistoryResource.cs, examples/csharp/src/Twilio/Rest/FlexApi/V1/Credential/NewCredentialsOptions.cs, examples/csharp/src/Twilio/Rest/FlexApi/V1/Credential/NewCredentialsResource.cs, examples/go/go-client/helper/rest/flex/v1/credentials_aws.go, examples/go/go-client/helper/rest/flex/v1/credentials_aws_history.go, examples/go/go-client/terraform/resources/flex/v1/README.md, examples/go/go-client/terraform/resources/flex/v1/api_default.go, examples/java/src/main/java/com/twilio/rest/flexapi/v1/credential/NewCredentialsCreator.java, examples/java/src/main/java/com/twilio/rest/flexapi/v1/credential/aws/HistoryFetcher.java, examples/node/lib/rest/api/v2010/account/call/feedbackCallSummary.ts, examples/node/lib/rest/flexApi/v1/credential/aws/history.ts, examples/node/lib/rest/flexApi/v1/credential/newCredentials.ts, examples/node/spec/unit/account/call.spec.ts, examples/node/spec/unit/credential.spec.ts, examples/spec/twilio_flex_v1.yaml, src/main/java/com/twilio/oai/TwilioCodegenAdapter.java, src/main/java/com/twilio/oai/TwilioNodeGenerator.java, src/main/resources/twilio-node/requestParam.mustache
Also fix double accountSid name.
https://github.com/twilio/twilio-node/pull/817
=> fix: properly serialize various parameters in node-oai

examples/node/lib/rest/api/v2010/account/call/feedbackCallSummary.ts, examples/node/lib/rest/flexApi/v1/call.ts, examples/node/lib/rest/flexApi/v1/credential/aws/history.ts, src/main/java/com/twilio/oai/PathUtils.java, src/main/java/com/twilio/oai/TwilioNodeGenerator.java, src/main/java/com/twilio/oai/common/ApplicationConstants.java, src/main/java/com/twilio/oai/resource/Resource.java, src/main/resources/twilio-node/api-single.mustache
https://github.com/twilio/twilio-node/pull/818
=> fix: properly handle 'parent params' in node-oai

examples/csharp/src/Twilio/Rest/Api/V2010/Account/Call/FeedbackCallSummaryResource.cs, examples/csharp/src/Twilio/Rest/Api/V2010/Account/CallOptions.cs, examples/csharp/src/Twilio/Rest/Api/V2010/Account/CallResource.cs, examples/csharp/src/Twilio/Rest/Api/V2010/AccountResource.cs, examples/csharp/unit-test/Rest/TwilioRestTest.cs, examples/go/go-client/helper/rest/api/v2010/accounts_calls.go, examples/go/go-client/helper/rest/api/v2010/model_test_response_object.go, examples/go/go-client/terraform/resources/api/v2010/README.md, examples/go/go-client/terraform/resources/api/v2010/accounts_calls_test.go, examples/go/go-client/terraform/resources/api/v2010/api_default.go, examples/java/integration-test/rest/APIIntegrationTest.java, examples/java/src/main/java/com/twilio/rest/api/v2010/Account.java, examples/java/src/main/java/com/twilio/rest/api/v2010/account/Call.java, examples/java/src/main/java/com/twilio/rest/api/v2010/account/CallCreator.java, examples/java/src/main/java/com/twilio/rest/api/v2010/account/call/FeedbackCallSummary.java, examples/java/unit-test/rest/TwilioRestTest.java, examples/node/lib/rest/api/v2010/account.ts, examples/node/lib/rest/api/v2010/account/call.ts, examples/node/lib/rest/api/v2010/account/call/feedbackCallSummary.ts, examples/node/spec/integration/apiIntegration.spec.ts, examples/node/spec/unit/account.spec.ts, examples/node/spec/unit/account/call.spec.ts, examples/spec/twilio_api_v2010.yaml
Closes: DII-732
Updated test and api fixture, to include decimal and a required HttpMethod type.
=> test: updating test for modified api fixture

examples/csharp/src/Twilio/Rest/Api/V2010/Account/Call/FeedbackCallSummaryResource.cs, examples/csharp/src/Twilio/Rest/Api/V2010/Account/CallResource.cs, examples/csharp/src/Twilio/Rest/Api/V2010/AccountResource.cs, examples/csharp/src/Twilio/Rest/FlexApi/V1/CallResource.cs, examples/csharp/src/Twilio/Rest/FlexApi/V1/Credential/Aws/HistoryResource.cs, examples/csharp/src/Twilio/Rest/FlexApi/V1/Credential/AwsResource.cs, examples/csharp/src/Twilio/Rest/FlexApi/V1/Credential/NewCredentialsResource.cs, examples/csharp/src/Twilio/Rest/Versionless/DeployedDevices/FleetResource.cs, examples/csharp/src/Twilio/Rest/Versionless/Understand/AssistantResource.cs, src/main/resources/twilio-csharp/Pagination.mustache, src/main/resources/twilio-csharp/resource/CreateResource.mustache, src/main/resources/twilio-csharp/resource/DeleteResource.mustache, src/main/resources/twilio-csharp/resource/FetchResource.mustache, src/main/resources/twilio-csharp/resource/ReadResource.mustache, src/main/resources/twilio-csharp/resource/UpdateResource.mustache
Fix spacing in csharp generated library
=> chore: fixed spacing issues in csharp

examples/csharp/src/Twilio/Rest/Api/V2010/Account/CallOptions.cs, src/main/resources/twilio-csharp/options/MethodsComments.mustache, src/main/resources/twilio-csharp/resource/ResponseModel.mustache
At some places junk characters were coming in comments because Quotes were not read properly.
Issue can be confirmed from:
examples/csharp/src/Twilio/Rest/Api/V2010/Account/CallOptions.cs
method: CreateCallOptions
=> chore: corrected the display of comment, removed junk characters

src/main/java/com/twilio/oai/DirectoryStructureService.java, src/main/java/com/twilio/oai/TwilioCsharpGenerator.java, src/main/java/com/twilio/oai/TwilioJavaGenerator.java, src/main/java/com/twilio/oai/common/Utility.java
Pulled out common code and refactored to fit both. No changes to generated code.
=> chore: refactor getRecordKey for Java and CSharp

examples/csharp/Dockerfile, examples/csharp/src/Twilio/Rest/Api/V2010/AccountOptions.cs, examples/csharp/src/Twilio/Rest/Api/V2010/AccountResource.cs, examples/spec/twilio_api_v2010.yaml, src/main/resources/twilio-csharp/Summary.mustache
https://github.com/twilio/twilio-csharp/pull/650
=> docs: update summaries with special characters in c#

examples/csharp/src/Twilio/Rest/Api/V2010/Account/Call/FeedbackCallSummaryOptions.cs, examples/csharp/src/Twilio/Rest/Api/V2010/Account/CallOptions.cs, examples/csharp/src/Twilio/Rest/Api/V2010/AccountOptions.cs, examples/csharp/src/Twilio/Rest/FlexApi/V1/CallOptions.cs, examples/csharp/src/Twilio/Rest/FlexApi/V1/Credential/Aws/HistoryOptions.cs, examples/csharp/src/Twilio/Rest/FlexApi/V1/Credential/AwsOptions.cs, examples/csharp/src/Twilio/Rest/FlexApi/V1/Credential/NewCredentialsOptions.cs, examples/csharp/src/Twilio/Rest/Versionless/DeployedDevices/FleetOptions.cs, src/main/resources/twilio-csharp/options/CreateOptions.mustache, src/main/resources/twilio-csharp/options/DeleteOptions.mustache, src/main/resources/twilio-csharp/options/FetchOptions.mustache, src/main/resources/twilio-csharp/options/ReadOptions.mustache, src/main/resources/twilio-csharp/options/UpdateOptions.mustache
Corrected line/spacing in c# comments in options file.
=> chore: refactored c# comments in options file

src/main/java/com/twilio/oai/Inflector.java, src/test/java/com/twilio/oai/InflectorTest.java
Removes wild cards and exceptional irregulars which are not needed with updated rules and logic. No changes to generated files.
=> feat: simplify the inflector logic

examples/php/src/Twilio/Rest/Api/V2010/Account/Call/FeedbackCallSummaryList.php, examples/php/src/Twilio/Rest/Api/V2010/Account/CallContext.php, examples/php/src/Twilio/Rest/Api/V2010/Account/CallInstance.php, examples/php/src/Twilio/Rest/Api/V2010/Account/CallList.php, examples/php/src/Twilio/Rest/Api/V2010/Account/CallOptions.php, examples/php/src/Twilio/Rest/Api/V2010/AccountList.php, examples/php/src/Twilio/Rest/FlexApi/V1/CallList.php, examples/php/src/Twilio/Rest/FlexApi/V1/Credential/Aws/HistoryList.php, examples/php/src/Twilio/Rest/FlexApi/V1/Credential/AwsList.php, examples/php/src/Twilio/Rest/FlexApi/V1/Credential/NewCredentialsList.php, examples/php/src/Twilio/Rest/FlexApi/V1/CredentialContext.php, examples/php/src/Twilio/Rest/FlexApi/V1/CredentialList.php, examples/php/src/Twilio/Rest/Versionless/DeployedDevices/FleetList.php, examples/php/src/Twilio/Rest/Versionless/Understand/AssistantList.php, src/main/java/com/twilio/oai/api/PhpApiResourceBuilder.java, src/main/java/com/twilio/oai/resource/ResourceMap.java, src/main/resources/twilio-php/context.mustache, src/main/resources/twilio-php/list.mustache
generate correct properties for list.php files 
=> fix:  domain list property annotations

examples/node/lib/rest/api/v2010/account.ts, examples/node/lib/rest/api/v2010/account/call.ts, examples/node/lib/rest/api/v2010/account/call/feedbackCallSummary.ts, examples/node/lib/rest/flexApi/v1/call.ts, examples/node/lib/rest/flexApi/v1/credential.ts, examples/node/lib/rest/flexApi/v1/credential/aws.ts, examples/node/lib/rest/flexApi/v1/credential/aws/history.ts, examples/node/lib/rest/flexApi/v1/credential/newCredentials.ts, examples/node/lib/rest/versionless/deployed_devices/fleet.ts, examples/node/lib/rest/versionless/understand/assistant.ts, examples/node/spec/unit/call.spec.ts, src/main/resources/twilio-node/api-single.mustache
Depends on https://github.com/twilio/twilio-node/pull/834 and https://github.com/twilio/twilio-node/pull/835
Generated changes: https://github.com/twilio/twilio-node/pull/836
=> feat: add path param validator to node-oai

src/main/java/com/twilio/oai/api/JavaApiResourceBuilder.java
fixes: https://issues.corp.twilio.com/browse/DII-796
The header params logic was missing for java, which caused the build to fail. Added the logic.
=> fix: adding missing logic for header params

examples/java/src/main/java/com/twilio/rest/api/v2010/AccountReader.java, examples/java/src/main/java/com/twilio/rest/flexapi/v1/credential/AwsReader.java, examples/java/unit-test/rest/TwilioRestTest.java, src/main/resources/twilio-java/creator.mustache, src/main/resources/twilio-java/deleter.mustache, src/main/resources/twilio-java/fetcher.mustache, src/main/resources/twilio-java/queryParams.mustache, src/main/resources/twilio-java/queryParamsFunc.mustache, src/main/resources/twilio-java/reader.mustache, src/main/resources/twilio-java/updater.mustache
Fixes issue https://github.com/twilio/twilio-java/issues/723
updating functionality for setting pageSize in twilio-java.
=> fix: fixed pageSize functionality

examples/php/tests/Twilio/Integration/Rest/TwilioRestExtTest.php, examples/php/tests/Twilio/Integration/Rest/TwilioRestFlexTest.php, examples/php/tests/Twilio/Integration/Rest/TwilioRestTest.php, examples/php/tests/Twilio/Integration/Rest/TwilioVersionLessTest.php
- Add PHP unit tests to increase test coverage
=> chore: increase PHP test coverage

src/main/java/com/twilio/oai/TwilioCsharpGenerator.java, src/main/java/com/twilio/oai/TwilioJavaGenerator.java, src/main/java/com/twilio/oai/TwilioNodeGenerator.java, src/main/java/com/twilio/oai/TwilioPhpGenerator.java, src/main/java/com/twilio/oai/TwilioPythonGenerator.java, src/main/java/com/twilio/oai/api/ApiResourceBuilder.java, src/main/java/com/twilio/oai/api/PhpApiResourceBuilder.java, src/main/java/com/twilio/oai/api/PhpDomainBuilder.java, src/main/java/com/twilio/oai/common/Utility.java, src/main/java/com/twilio/oai/resolver/ConfigurationSegment.java, src/main/java/com/twilio/oai/resolver/IConventionMapper.java, src/main/java/com/twilio/oai/resolver/LanguageConventionResolver.java, src/main/java/com/twilio/oai/resolver/LanguageParamResolver.java, src/main/java/com/twilio/oai/resolver/LanguagePropertyResolver.java, src/main/java/com/twilio/oai/resolver/Resolver.java, src/main/java/com/twilio/oai/resolver/common/CodegenModelComplexResolver.java, src/main/java/com/twilio/oai/resolver/common/CodegenModelDataTypeResolver.java, src/main/java/com/twilio/oai/resolver/common/CodegenParameterDataTypeResolver.java, src/main/java/com/twilio/oai/resolver/java/JavaParameterResolver.java, src/main/java/com/twilio/oai/resolver/java/JavaPropertyResolver.java, src/main/java/com/twilio/oai/resolver/php/PhpParameterResolver.java, src/main/java/com/twilio/oai/template/AbstractApiActionTemplate.java, src/main/java/com/twilio/oai/template/JavaApiActionTemplate.java, src/main/java/com/twilio/oai/template/PhpApiActionTemplate.java, src/main/resources/config/csharp.json, src/main/resources/config/java.json, src/main/resources/config/twilio-php.json
No impact to generated libraries. Synchronizes the Java and PHP config files to match what's in twilio-oai: https://github.com/twilio/twilio-oai/tree/main/types
=> chore: refactor the configuration segment logic

src/main/java/com/twilio/oai/Inflector.java, src/test/java/com/twilio/oai/InflectorTest.java
When generating a class named Primitive it sets the name to Primitife because of the singular rules in place.
Added an exception for this case.
=> fix: Singular of primitives is primitive, not primitife

examples/php/tests/Twilio/Integration/Rest/TwilioRestExtTest.php, examples/php/tests/Twilio/Integration/Rest/TwilioRestFlexTest.php, examples/php/tests/Twilio/Integration/Rest/TwilioRestTest.php, examples/php/tests/Twilio/Integration/Rest/TwilioVersionLessTest.php
Added more unit test cases to increase the code coverage.
=> chore: add testCases

examples/node/lib/rest/api/V2010.ts, examples/node/lib/rest/api/v2010/account.ts, examples/node/lib/rest/api/v2010/account/call.ts, examples/node/lib/rest/api/v2010/account/call/feedbackCallSummary.ts, examples/node/lib/rest/flexApi/V1.ts, examples/node/lib/rest/flexApi/v1/call.ts, examples/node/lib/rest/flexApi/v1/credential/aws.ts, examples/node/lib/rest/flexApi/v1/credential/aws/history.ts, examples/node/lib/rest/flexApi/v1/credential/newCredentials.ts, examples/node/lib/rest/versionless/DeployedDevices.ts, examples/node/lib/rest/versionless/Understand.ts, examples/node/lib/rest/versionless/deployed_devices/fleet.ts, examples/node/lib/rest/versionless/understand/assistant.ts, src/main/resources/twilio-node/api-single.mustache, src/main/resources/twilio-node/listOperationsOptions.mustache, src/main/resources/twilio-node/operationSignature.mustache, src/main/resources/twilio-node/version.mustache
JIRA - [DI-2350](https://issues.corp.twilio.com/browse/DI-2350)
With TSDoc, we don't need to define types with @param and @returns tags. Also @property tags are not present, they are auto defined, but the docstrings need to be defined alongside property declaration. 
Generated changes - https://github.com/twilio/twilio-node/pull/866
=> feat: TSDoc changes for generated code

examples/node/Dockerfile, examples/node/lib/rest/api/v2010/account.ts, examples/node/lib/rest/api/v2010/account/call.ts, examples/node/lib/rest/api/v2010/account/call/feedbackCallSummary.ts, examples/node/lib/rest/flexApi/v1/call.ts, examples/node/lib/rest/flexApi/v1/credential.ts, examples/node/lib/rest/flexApi/v1/credential/aws.ts, examples/node/lib/rest/flexApi/v1/credential/aws/history.ts, examples/node/lib/rest/flexApi/v1/credential/newCredentials.ts, examples/node/lib/rest/versionless/deployed_devices/fleet.ts, examples/node/lib/rest/versionless/understand/assistant.ts, src/main/resources/twilio-node/api-single.mustache, src/main/resources/twilio-node/operation.mustache, src/main/resources/twilio-node/responseModel.mustache
Corrects some strict Typescript issues and simplifies the implementation.
https://github.com/twilio/twilio-node/pull/860
=> fix: refactor the instance implementation in node

examples/node/lib/rest/flexApi/v1/credential/aws/history.ts, examples/node/lib/rest/flexApi/v1/credential/newCredentials.ts, src/main/resources/config/node.json
Internal JIRA: DI-2443(https://issues.corp.twilio.com/browse/DI-2443)
Generated Changes: https://github.com/twilio/twilio-node/pull/873
=> chore: Use Record type

src/main/java/com/twilio/oai/EnumsResolver.java, src/main/java/com/twilio/oai/PathUtils.java, src/main/java/com/twilio/oai/api/ApiResources.java, src/main/java/com/twilio/oai/common/Utility.java, src/main/java/com/twilio/oai/resolver/DataSanitizer.java, src/main/java/com/twilio/oai/resolver/LanguageParamResolver.java, src/main/java/com/twilio/oai/resolver/LanguagePropertyResolver.java, src/main/java/com/twilio/oai/resolver/common/CodegenModelComplexResolver.java, src/main/java/com/twilio/oai/resolver/common/CodegenModelContainerDataTypeResolver.java, src/main/java/com/twilio/oai/resolver/common/CodegenModelDataTypeResolver.java, src/main/java/com/twilio/oai/resolver/common/CodegenParameterContainerDataTypeResolver.java, src/main/java/com/twilio/oai/resolver/common/CodegenParameterDataTypeResolver.java, src/main/java/com/twilio/oai/resolver/csharp/CSharpResolver.java, src/main/java/com/twilio/oai/resolver/csharp/CodegenModelComplexResolver.java, src/main/java/com/twilio/oai/resolver/csharp/CodegenModelContainerDataTypeResolver.java, src/main/java/com/twilio/oai/resolver/csharp/CodegenModelDataTypeResolver.java, src/main/java/com/twilio/oai/resolver/csharp/CodegenModelResolver.java, src/main/java/com/twilio/oai/resolver/csharp/CodegenParameterContainerDataTypeResolver.java, src/main/java/com/twilio/oai/resolver/csharp/CodegenParameterDataTypeResolver.java, src/main/java/com/twilio/oai/resolver/csharp/CodegenParameterResolver.java
=> chore: code refactor with Lombok

scripts/prism.sh
Relates to https://github.com/docker/compose/issues/10085
=> test: look for all services, including those that are stopped, when checking status

examples/ruby/spec/unit/twilio_api_spec.rb
Changes for DII-754. Added test to assert date serialization
=> test: adding test for serialization for ruby

src/main/resources/twilio-java/postParams.mustache
In the [yoyodyne generated](https://github.com/twilio/twilio-java/blob/27834776878ee2ce3d15beeb6680ac4f42a3c60e/src/main/java/com/twilio/rest/conversations/v1/conversation/WebhookCreator.java#L187) code of twilio-java, the `configurationMethod` and other similar properties were translated as `Configuration.Method` while in [oai-generated](https://github.com/twilio/twilio-java/blob/main/src/main/java/com/twilio/rest/conversations/v1/conversation/WebhookCreator.java#L119) code, these are translated as `ConfigurationMethod`.
These properties if translated as `ConfigurationMethod` are ignored by REST API.
It should be `Configuration.Method` or it won't work.
Related PR: https://github.com/twilio/twilio-java/pull/729
=> fix: reference baseName instead of paramName

examples/node/src/rest/Twilio.ts
Relates to https://github.com/twilio/twilio-node/pull/907
=> fix: update node exports for backwards-compatibility

examples/node/src/rest/api/v2010/account.ts, examples/node/src/rest/api/v2010/account/call.ts, examples/node/src/rest/api/v2010/account/call/feedbackCallSummary.ts, src/main/resources/config/node.json, src/main/resources/twilio-node/imports.mustache
https://github.com/twilio/twilio-node/pull/910
=> fix: use relative root for library type imports in node

examples/csharp/src/Twilio/Rest/Api/V2010/AccountResource.cs, examples/csharp/src/Twilio/Rest/FlexApi/V1/Credential/AwsResource.cs, examples/csharp/src/Twilio/Rest/Versionless/Understand/AssistantResource.cs, examples/spec/twilio_api_v2010.yaml, examples/spec/twilio_flex_v1.yaml, examples/spec/twilio_versionless.yaml, src/main/java/com/twilio/oai/DirectoryStructureService.java, src/main/resources/twilio-csharp/resource/MethodsComments.mustache, src/main/resources/twilio-csharp/resource/ReadResource.mustache
Also fixes comment ordering in some C# files.
=> feat: handle additional pagination parameters

examples/python/twilio/rest/api/v2010/account.py, examples/python/twilio/rest/api/v2010/account/call.py, examples/python/twilio/rest/flex_api/v1/credential.py, examples/python/twilio/rest/flex_api/v1/credential/aws.py
Local changes to api-single.mustache caused unwanted changes to python examples
=> test: regenerate python examples to fix test

examples/ruby/lib/twilio-ruby/rest/api/v2010/account.rb, examples/ruby/lib/twilio-ruby/rest/api/v2010/account/call.rb, examples/ruby/lib/twilio-ruby/rest/api/v2010/account/call/feedback_call_summary.rb, examples/ruby/lib/twilio-ruby/rest/flex_api/v1/call.rb, examples/ruby/lib/twilio-ruby/rest/flex_api/v1/credential.rb, examples/ruby/lib/twilio-ruby/rest/flex_api/v1/credential/aws.rb, examples/ruby/lib/twilio-ruby/rest/flex_api/v1/credential/aws/history.rb, examples/ruby/lib/twilio-ruby/rest/flex_api/v1/credential/new_credentials.rb, examples/ruby/lib/twilio-ruby/rest/versionless/deployed_devices/fleet.rb, examples/ruby/lib/twilio-ruby/rest/versionless/understand/assistant.rb, src/main/java/com/twilio/oai/api/RubyApiResourceBuilder.java, src/main/java/com/twilio/oai/resolver/ruby/RubyParameterResolver.java, src/main/resources/config/ruby.json, src/main/resources/twilio-ruby/context.mustache, src/main/resources/twilio-ruby/contextMethodParams.mustache, src/main/resources/twilio-ruby/instance.mustache, src/main/resources/twilio-ruby/list.mustache, src/main/resources/twilio-ruby/methods.mustache, src/main/resources/twilio-ruby/version.mustache
-  fix issues in instance files, JIRA ticket: [link](https://issues.corp.twilio.com/browse/DII-861)
- Set correct order of params in CRUD operations
- Resolve `Integer` as `String`
- Serialize Array of objects and array of strings appropriately : JIRA ticket: [link](https://issues.corp.twilio.com/browse/DII-853)
- Convert dataType from `Array<String>` to `Array[String]`, and `Array<Object>` to `Array[Hash]`
=> fix: CRUD operations in instance files

src/main/java/com/twilio/oai/TwilioTerraformGenerator.java
https://github.com/twilio/terraform-provider-twilio/pull/125
=> fix: don't group incompatible APIs together in Terraform

examples/python/twilio/rest/api/v2010/__init__.py, src/main/resources/twilio-python/version.mustache
Matches existing implementation: https://github.com/twilio/twilio-python/blob/c57516c0744b8c1831063fc67ff7122b69688c05/twilio/rest/api/v2010/__init__.py#L47
https://github.com/twilio/twilio-python/pull/655
=> feat: add python account setter

examples/node/src/rest/api/v2010/account.ts, examples/node/src/rest/api/v2010/account/call.ts, examples/node/src/rest/api/v2010/account/call/feedbackCallSummary.ts, examples/node/src/rest/flexApi/v1/credential/newCredentials.ts, src/main/resources/twilio-node/model.mustache
https://github.com/twilio/twilio-node/pull/917
=> feat: export enum types in node

examples/python/twilio/rest/api/v2010/account/__init__.py, examples/python/twilio/rest/api/v2010/account/call/__init__.py, examples/python/twilio/rest/api/v2010/account/call/feedback_call_summary.py, examples/python/twilio/rest/flex_api/v1/call.py, examples/python/twilio/rest/flex_api/v1/credential/__init__.py, examples/python/twilio/rest/flex_api/v1/credential/aws/__init__.py, examples/python/twilio/rest/flex_api/v1/credential/aws/history.py, examples/python/twilio/rest/flex_api/v1/credential/new_credentials.py, examples/python/twilio/rest/versionless/deployed_devices/fleet.py, examples/python/twilio/rest/versionless/understand/assistant.py, src/main/java/com/twilio/oai/TwilioPythonGenerator.java, src/main/java/com/twilio/oai/api/PythonApiResourceBuilder.java, src/main/resources/config/python.json, src/main/resources/twilio-python/api-single.mustache, src/main/resources/twilio-python/contextMethods.handlebars, src/main/resources/twilio-python/listOperations.handlebars, src/main/resources/twilio-python/pagination.handlebars
Internal JIRA ticket: [DI-2451](https://issues.corp.twilio.com/browse/DI-2451)
Generated Changes: https://github.com/twilio/twilio-python/pull/658
=> feat: create, get, call methods

scripts/build_twilio_library.py
Added ruby as a valid language param in build twilio library script
=> chore: add ruby language for twilio oai generation

.gitignore, scripts/build_twilio_library.py, scripts/generate.sh
Runs multi-threaded and reduces generation time.
https://github.com/OpenAPITools/openapi-generator/blob/master/docs/usage.md#user-content-batch
=> feat: run generation in batch mode

examples/python/twilio/rest/flex_api/v1/credential/aws/history.py, src/main/resources/twilio-python/context.handlebars
Generated changes: https://github.com/twilio/twilio-python/pull/663
=> fix: include serialize.prefixed_collapsible_map

examples/python/Dockerfile, examples/python/tests/integration/api_integration_test.py, examples/python/tests/unit/account/call_test.py, examples/python/tests/unit/account_test.py, examples/python/tests/unit/credential_test.py, examples/python/tests/unit/flex_call_test.py, examples/python/twilio/rest/api/__init__.py, examples/python/twilio/rest/flex_api/__init__.py
Internal Jira Link: [DI-2458](https://issues.corp.twilio.com/browse/DI-2458)
=> test: Add python integration test

examples/python/twilio/rest/api/v2010/account/__init__.py, examples/python/twilio/rest/api/v2010/account/call/__init__.py, examples/python/twilio/rest/api/v2010/account/call/feedback_call_summary.py, src/main/java/com/twilio/oai/TwilioCsharpGenerator.java, src/main/java/com/twilio/oai/TwilioJavaGenerator.java, src/main/java/com/twilio/oai/TwilioPythonGenerator.java, src/main/java/com/twilio/oai/api/ApiResourceBuilder.java, src/main/java/com/twilio/oai/templating/TwilioHandlebarsEngineAdapter.java, src/main/java/com/twilio/oai/templating/handlebars/TwilioHelpers.java, src/main/java/com/twilio/oai/templating/mustache/ReplaceHyphenLambda.java, src/main/java/com/twilio/oai/templating/mustache/TitleCaseLambda.java, src/main/resources/META-INF/services/org.openapitools.codegen.api.TemplatingEngineAdapter, src/main/resources/twilio-python/instance.handlebars, src/main/resources/twilio-python/model.handlebars, src/main/resources/twilio-python/model.mustache
Also creates handlebar engine extension for adding custom helper methods.
https://github.com/twilio/twilio-python/pull/664
=> feat: add python enum classes

examples/python/twilio/rest/api/v2010/account/__init__.py, examples/python/twilio/rest/api/v2010/account/call/__init__.py, examples/python/twilio/rest/api/v2010/account/call/feedback_call_summary.py, examples/python/twilio/rest/flex_api/v1/credential/new_credentials.py, src/main/java/com/twilio/oai/api/FluentApiResourceBuilder.java, src/main/java/com/twilio/oai/api/NodeApiResourceBuilder.java, src/main/java/com/twilio/oai/api/PythonApiResourceBuilder.java
https://github.com/twilio/twilio-python/pull/670
=> fix: correct the param typing for enums in python

examples/python/twilio/rest/api/v2010/__init__.py, examples/python/twilio/rest/flex_api/v1/__init__.py, examples/python/twilio/rest/versionless/deployed_devices/__init__.py, examples/python/twilio/rest/versionless/understand/__init__.py, src/main/resources/twilio-python/version.mustache
[DI-2457](https://issues.corp.twilio.com/browse/DI-2457)
Generated changes- https://github.com/twilio/twilio-python/pull/672
=> feat: Adding remaining docstrings for python

examples/python/tests/unit/account_test.py
Internal JIRA Link: [DI-2455](https://issues.corp.twilio.com/browse/DI-2455)
=> test: python date range support

examples/python/twilio/rest/api/v2010/account/__init__.py, examples/python/twilio/rest/api/v2010/account/call/__init__.py, examples/python/twilio/rest/api/v2010/account/call/feedback_call_summary.py, examples/python/twilio/rest/flex_api/v1/call.py, examples/python/twilio/rest/flex_api/v1/credential/__init__.py, examples/python/twilio/rest/flex_api/v1/credential/aws/__init__.py, examples/python/twilio/rest/flex_api/v1/credential/aws/history.py, examples/python/twilio/rest/flex_api/v1/credential/new_credentials.py, examples/python/twilio/rest/versionless/deployed_devices/fleet.py, examples/python/twilio/rest/versionless/understand/assistant.py, src/main/java/com/twilio/oai/TwilioPythonGenerator.java, src/main/java/com/twilio/oai/api/PythonApiResourceBuilder.java, src/main/resources/twilio-python/api-single.mustache, src/main/resources/twilio-python/context.handlebars, src/main/resources/twilio-python/listOperations.handlebars
Key Changes:
- Add import Date statement due to type hints
- Instance class is now above Context class to support enum referencing in typehints
- Serialize object within Serialize Map if datatype is Object
- Change `a2_p_profile_bundle_sid` to `a2p_profile_bundle_sid`
- Generate Create, Update, Fetch function in List class properly
- Generate Context class properties properly
=> fix: python-tests

src/main/resources/twilio-python/listOperations.handlebars
Generated changes: https://github.com/twilio/twilio-python/pull/674
=> fix: call fetch for python fetch operations

examples/python/Dockerfile-prettier, examples/python/twilio/rest/api/v2010/account/__init__.py, examples/python/twilio/rest/api/v2010/account/call/__init__.py, examples/python/twilio/rest/api/v2010/account/call/feedback_call_summary.py, examples/python/twilio/rest/flex_api/v1/call.py, examples/python/twilio/rest/flex_api/v1/credential/__init__.py, examples/python/twilio/rest/flex_api/v1/credential/aws/__init__.py, examples/python/twilio/rest/flex_api/v1/credential/aws/history.py, examples/python/twilio/rest/flex_api/v1/credential/new_credentials.py, examples/python/twilio/rest/versionless/deployed_devices/fleet.py, examples/python/twilio/rest/versionless/understand/assistant.py, src/main/resources/twilio-python/api-single.mustache, src/main/resources/twilio-python/instance.handlebars
Fixes pyright errors.
https://github.com/twilio/twilio-python/pull/680
=> chore: allow 'None' for non-parent params in python

examples/python/Dockerfile, examples/python/twilio/rest/api/__init__.py, examples/python/twilio/rest/api/v2010/__init__.py, examples/python/twilio/rest/api/v2010/account/__init__.py, examples/python/twilio/rest/flex_api/__init__.py, examples/python/twilio/rest/flex_api/v1/__init__.py, examples/python/twilio/rest/flex_api/v1/credential/aws/__init__.py, examples/python/twilio/rest/versionless/__init__.py, examples/python/twilio/rest/versionless/deployed_devices/__init__.py, examples/python/twilio/rest/versionless/understand/__init__.py, examples/python/twilio/rest/versionless/understand/assistant.py, src/main/resources/twilio-python/pagination.handlebars, src/main/resources/twilio-python/version.mustache
Provides for better type checking.
https://github.com/twilio/twilio-python/pull/686
=> chore: refactor base initialization in python

examples/python/Dockerfile, examples/python/twilio/rest/api/v2010/__init__.py, examples/python/twilio/rest/api/v2010/account/__init__.py, examples/python/twilio/rest/api/v2010/account/call/__init__.py, examples/python/twilio/rest/api/v2010/account/call/feedback_call_summary.py, examples/python/twilio/rest/flex_api/v1/__init__.py, examples/python/twilio/rest/flex_api/v1/call.py, examples/python/twilio/rest/flex_api/v1/credential/__init__.py, examples/python/twilio/rest/flex_api/v1/credential/aws/__init__.py, examples/python/twilio/rest/flex_api/v1/credential/aws/history.py, examples/python/twilio/rest/flex_api/v1/credential/new_credentials.py, examples/python/twilio/rest/versionless/deployed_devices/__init__.py, examples/python/twilio/rest/versionless/deployed_devices/fleet.py, examples/python/twilio/rest/versionless/understand/__init__.py, examples/python/twilio/rest/versionless/understand/assistant.py, src/main/resources/twilio-python/api-single.mustache, src/main/resources/twilio-python/context.handlebars, src/main/resources/twilio-python/instance.handlebars, src/main/resources/twilio-python/listOperations.handlebars, src/main/resources/twilio-python/version.mustache
Provides for better type checking.
https://github.com/twilio/twilio-python/pull/688
=> fix: mark dependents as optional and drop empty path solutions in python

examples/python/twilio/rest/api/v2010/__init__.py, examples/python/twilio/rest/api/v2010/account/__init__.py, examples/python/twilio/rest/api/v2010/account/call/__init__.py, examples/python/twilio/rest/api/v2010/account/call/feedback_call_summary.py, examples/python/twilio/rest/flex_api/v1/call.py, examples/python/twilio/rest/flex_api/v1/credential/__init__.py, examples/python/twilio/rest/flex_api/v1/credential/aws/__init__.py, examples/python/twilio/rest/flex_api/v1/credential/aws/history.py, examples/python/twilio/rest/flex_api/v1/credential/new_credentials.py, examples/python/twilio/rest/versionless/deployed_devices/fleet.py, examples/python/twilio/rest/versionless/understand/assistant.py, src/main/java/com/twilio/oai/api/PythonApiResourceBuilder.java, src/main/resources/twilio-python/api-single.mustache, src/main/resources/twilio-python/context.handlebars, src/main/resources/twilio-python/contextMethods.handlebars, src/main/resources/twilio-python/instance.handlebars, src/main/resources/twilio-python/listOperations.handlebars, src/main/resources/twilio-python/pagination.handlebars, src/main/resources/twilio-python/version.mustache
https://github.com/twilio/twilio-python/pull/693
=> feat: add return types to rest classes in python

examples/python/twilio/rest/flex_api/v1/credential/aws/history.py, examples/python/twilio/rest/flex_api/v1/credential/new_credentials.py, src/main/resources/config/python.json, src/main/resources/twilio-python/api-single.mustache
https://github.com/twilio/twilio-python/pull/695
=> fix: update the Dict property types in python

examples/python/Dockerfile, examples/python/setup.cfg, examples/python/sonar-project.properties
[Sonarcloud Coverage](https://sonarcloud.io/summary/new_code?id=twilio_twilio-oai-generator-python&pullRequest=481)
=> chore: report proper coverage for python sonarcloud  

examples/python/twilio/rest/api/v2010/account/__init__.py, examples/python/twilio/rest/api/v2010/account/call/__init__.py, examples/python/twilio/rest/api/v2010/account/call/feedback_call_summary.py, examples/python/twilio/rest/flex_api/v1/call.py, examples/python/twilio/rest/flex_api/v1/credential/aws/__init__.py, examples/python/twilio/rest/flex_api/v1/credential/aws/history.py, examples/python/twilio/rest/flex_api/v1/credential/new_credentials.py, examples/python/twilio/rest/versionless/deployed_devices/fleet.py, examples/python/twilio/rest/versionless/understand/assistant.py, src/main/resources/twilio-python/api-single.mustache, src/main/resources/twilio-python/context.handlebars, src/main/resources/twilio-python/contextMethods.handlebars, src/main/resources/twilio-python/instance.handlebars, src/main/resources/twilio-python/listOperations.handlebars, src/main/resources/twilio-python/pagination.handlebars
https://github.com/twilio/twilio-python/pull/699
=> feat: add more types for the generated rest classes in python

examples/python/twilio/rest/flex_api/v1/credential/new_credentials.py, scripts/build_twilio_library.py, scripts/generate.sh
https://github.com/twilio/twilio-python/pull/700
=> fix: add form model generation for python

examples/python/tests/integration/api_integration_test.py, examples/python/twilio/rest/api/v2010/account/__init__.py, examples/python/twilio/rest/flex_api/v1/credential/aws/__init__.py, examples/python/twilio/rest/versionless/understand/assistant.py, src/main/resources/twilio-python/api-single.mustache, src/main/resources/twilio-python/listOperations.handlebars
https://github.com/twilio/twilio-python/pull/701
=> fix: correct the stream and list types in python

examples/csharp/src/Twilio/Rest/FlexApi/V1/Credential/Aws/HistoryOptions.cs, examples/csharp/src/Twilio/Rest/FlexApi/V1/Credential/Aws/HistoryResource.cs, examples/go/go-client/helper/rest/flex/v1/README.md, examples/go/go-client/helper/rest/flex/v1/credentials_aws_history.go, examples/java/src/main/java/com/twilio/rest/flexapi/v1/credential/aws/History.java, examples/java/src/main/java/com/twilio/rest/flexapi/v1/credential/aws/HistoryFetcher.java, examples/node/spec/unit/credential.spec.ts, examples/node/src/rest/flexApi/v1/credential/aws/history.ts, examples/php/src/Twilio/Rest/FlexApi/V1/Credential/Aws/HistoryContext.php, examples/php/src/Twilio/Rest/FlexApi/V1/Credential/Aws/HistoryInstance.php, examples/php/src/Twilio/Rest/FlexApi/V1/Credential/Aws/HistoryList.php, examples/php/src/Twilio/Rest/FlexApi/V1/Credential/AwsContext.php, examples/php/src/Twilio/Rest/FlexApi/V1/Credential/AwsInstance.php, examples/php/src/Twilio/Rest/FlexApi/V1/Credential/AwsList.php, examples/php/src/Twilio/Rest/FlexApi/V1/Credential/AwsOptions.php, examples/python/tests/unit/credential_test.py, examples/python/twilio/rest/flex_api/v1/credential/aws/history.py, examples/ruby/lib/twilio-ruby/rest/flex_api/v1/credential/aws.rb, examples/ruby/lib/twilio-ruby/rest/flex_api/v1/credential/aws/history.rb, examples/ruby/spec/unit/twilio_flex_spec.rb, examples/spec/twilio_flex_v1.yaml, src/main/java/com/twilio/oai/CodegenUtils.java, src/main/java/com/twilio/oai/PathUtils.java, src/main/java/com/twilio/oai/TwilioJavaGenerator.java, src/test/java/com/twilio/oai/PathUtilsTest.java
- Add logic to find pathType using URL 
- Add logic to find enum properties using allowedValues field in properties and parameters 
- fix wrong flex-api.yaml history url and update example files
=> fix: replace logic to find pathType operator and enum properties

examples/csharp/src/Twilio/Rest/FlexApi/V1/Credential/Aws/HistoryOptions.cs, examples/csharp/src/Twilio/Rest/FlexApi/V1/Credential/Aws/HistoryResource.cs, examples/go/go-client/helper/rest/flex/v1/README.md, examples/go/go-client/helper/rest/flex/v1/credentials_aws_history.go, examples/java/src/main/java/com/twilio/rest/flexapi/v1/credential/aws/History.java, examples/java/src/main/java/com/twilio/rest/flexapi/v1/credential/aws/HistoryFetcher.java, examples/node/spec/unit/credential.spec.ts, examples/node/src/rest/flexApi/v1/credential/aws/history.ts, examples/php/src/Twilio/Rest/FlexApi/V1/Credential/Aws/HistoryContext.php, examples/php/src/Twilio/Rest/FlexApi/V1/Credential/Aws/HistoryInstance.php, examples/php/src/Twilio/Rest/FlexApi/V1/Credential/Aws/HistoryList.php, examples/php/src/Twilio/Rest/FlexApi/V1/Credential/AwsContext.php, examples/php/src/Twilio/Rest/FlexApi/V1/Credential/AwsInstance.php, examples/php/src/Twilio/Rest/FlexApi/V1/Credential/AwsList.php, examples/php/src/Twilio/Rest/FlexApi/V1/Credential/AwsOptions.php, examples/python/tests/unit/credential_test.py, examples/python/twilio/rest/flex_api/v1/credential/aws/history.py, examples/ruby/lib/twilio-ruby/rest/flex_api/v1/credential/aws.rb, examples/ruby/lib/twilio-ruby/rest/flex_api/v1/credential/aws/history.rb, examples/ruby/spec/unit/twilio_flex_spec.rb, examples/spec/twilio_flex_v1.yaml, src/main/java/com/twilio/oai/PathUtils.java
=> fix: pathItem fetch logic

examples/ruby/lib/twilio-ruby/rest/api/v2010/account.rb, examples/ruby/lib/twilio-ruby/rest/api/v2010/account/call.rb, examples/ruby/spec/unit/twilio_api_spec.rb, examples/spec/twilio_api_v2010.yaml, src/main/java/com/twilio/oai/DirectoryStructureService.java, src/main/java/com/twilio/oai/PathUtils.java, src/main/java/com/twilio/oai/api/RubyApiResourceBuilder.java, src/main/java/com/twilio/oai/common/ApplicationConstants.java, src/main/resources/twilio-ruby/context.mustache, src/test/java/com/twilio/oai/PathUtilsTest.java
Fixes [DII-935](https://issues.corp.twilio.com/browse/DII-935)
This PR: 
Is dependent on: [yps #151](https://code.hq.twilio.com/twilio/yps/pull/151)
Processes the [dependents](https://code.hq.twilio.com/twilio/api-definitions/blob/cfc12878ee1d3ae15758585b32ba2aa202c28aab/base/api/v2010/account.json#L88) from the spec files, after yps adds them in the vendor extensions of all resources. 
=> feat: process dependent values in twilio-oai-generator

Makefile, examples/csharp/src/Twilio/Rest/Api/V2010/Account/Call/FeedbackCallSummaryResource.cs, examples/csharp/src/Twilio/Rest/Api/V2010/Account/CallResource.cs, examples/csharp/src/Twilio/Rest/Api/V2010/AccountResource.cs, examples/go/go-client/helper/rest/api/v2010/model_test_response_object.go, examples/java/src/main/java/com/twilio/rest/api/v2010/Account.java, examples/java/src/main/java/com/twilio/rest/api/v2010/account/Call.java, examples/java/src/main/java/com/twilio/rest/api/v2010/account/call/FeedbackCallSummary.java, examples/node/src/rest/api/v2010/account.ts, examples/node/src/rest/api/v2010/account/call.ts, examples/node/src/rest/api/v2010/account/call/feedbackCallSummary.ts, examples/php/src/Twilio/Rest/Api/V2010/Account/Call/FeedbackCallSummaryInstance.php, examples/php/src/Twilio/Rest/Api/V2010/Account/CallInstance.php, examples/php/src/Twilio/Rest/Api/V2010/AccountInstance.php, examples/python/twilio/rest/api/v2010/account/__init__.py, examples/python/twilio/rest/api/v2010/account/call/__init__.py, examples/python/twilio/rest/api/v2010/account/call/feedback_call_summary.py, examples/ruby/lib/twilio-ruby/rest/api/v2010/account.rb, examples/ruby/lib/twilio-ruby/rest/api/v2010/account/call.rb, examples/ruby/lib/twilio-ruby/rest/api/v2010/account/call/feedback_call_summary.rb, examples/spec/twilio_api_v2010.yaml, src/main/java/com/twilio/oai/TwilioPythonGenerator.java, src/main/java/com/twilio/oai/common/ApplicationConstants.java, src/main/java/com/twilio/oai/resolver/python/PythonPropertyResolver.java
Closes: https://issues.corp.twilio.com/browse/DII-971
Updating the \_from param in python to from_. This is set by default from openApiGenerator, we need to update it form from_ for backward compatibility
=> fix: update python param name

src/main/java/com/twilio/oai/resolver/python/PythonPropertyResolver.java
=> fix: fix null pointer exception

examples/java/Dockerfile
Add org.json dependency after cloning twilio-java for running test cases
=> fix: adding org.json for testing

src/main/java/com/twilio/oai/TwilioCodegenAdapter.java
=> fix: replace classloader to thread contextclassloader

src/main/java/com/twilio/oai/TwilioCodegenAdapter.java
=> fix: toggle jar file path

src/main/java/com/twilio/oai/api/JavaApiResourceBuilder.java
[DII-1000](https://issues.corp.twilio.com/browse/DII-1000) Java signature list for constructor addition doesnt handle duplicates
=> fix: removing duplicate constructors from generation

src/main/java/com/twilio/oai/api/ApiResourceBuilder.java, src/main/java/com/twilio/oai/api/JavaApiResourceBuilder.java, src/main/java/com/twilio/oai/api/JavaApiResources.java, src/main/java/com/twilio/oai/resolver/java/JavaConventionResolver.java, src/main/resources/twilio-java/api.mustache, src/main/resources/twilio-java/creator.mustache, src/main/resources/twilio-java/models.mustache, src/main/resources/twilio-java/postParams_body.mustache
Serialization code for json body. Custom serialization is not handled.
=> java: added serialization code

examples/java/src/main/java/com/twilio/rest/api/v2010/Account.java, examples/java/src/main/java/com/twilio/rest/api/v2010/account/Call.java, examples/java/src/main/java/com/twilio/rest/api/v2010/account/call/FeedbackCallSummary.java, examples/java/src/main/java/com/twilio/rest/flexapi/v1/Call.java, examples/java/src/main/java/com/twilio/rest/flexapi/v1/credential/Aws.java, examples/java/src/main/java/com/twilio/rest/flexapi/v1/credential/NewCredentials.java, examples/java/src/main/java/com/twilio/rest/flexapi/v1/credential/aws/History.java, examples/java/src/main/java/com/twilio/rest/versionless/deployedDevices/Fleet.java, examples/java/src/main/java/com/twilio/rest/versionless/understand/Assistant.java, src/main/java/com/twilio/oai/JsonRequestBodyResolver.java, src/main/java/com/twilio/oai/api/JavaApiResourceBuilder.java, src/main/java/com/twilio/oai/resolver/LanguagePropertyResolver.java, src/main/java/com/twilio/oai/resolver/java/JavaConventionResolver.java, src/main/resources/config/java.json, src/main/resources/twilio-java/api.mustache, src/main/resources/twilio-java/models.mustache, src/main/resources/twilio-java/postParams_body.mustache, src/main/resources/twilio-java/responseModel.mustache
Added custom serialization on json ingress models.
=> added custom serialization

src/main/java/com/twilio/oai/TwilioCodegenAdapter.java
Changes to support product.xxx.twilio.com server url format in open api
=> fix: support different server url format

examples/java/src/main/java/com/twilio/rest/api/v2010/Account.java, examples/java/src/main/java/com/twilio/rest/api/v2010/AccountCreator.java, examples/java/src/main/java/com/twilio/rest/api/v2010/AccountUpdater.java, examples/java/src/main/java/com/twilio/rest/api/v2010/account/Call.java, examples/java/src/main/java/com/twilio/rest/api/v2010/account/CallCreator.java, examples/java/src/main/java/com/twilio/rest/api/v2010/account/call/FeedbackCallSummary.java, examples/java/src/main/java/com/twilio/rest/api/v2010/account/call/FeedbackCallSummaryUpdater.java, examples/java/src/main/java/com/twilio/rest/flexapi/v1/Call.java, examples/java/src/main/java/com/twilio/rest/flexapi/v1/CallUpdater.java, examples/java/src/main/java/com/twilio/rest/flexapi/v1/credential/Aws.java, examples/java/src/main/java/com/twilio/rest/flexapi/v1/credential/AwsUpdater.java, examples/java/src/main/java/com/twilio/rest/flexapi/v1/credential/NewCredentials.java, examples/java/src/main/java/com/twilio/rest/flexapi/v1/credential/NewCredentialsCreator.java, examples/java/src/main/java/com/twilio/rest/flexapi/v1/credential/aws/History.java, examples/java/src/main/java/com/twilio/rest/versionless/deployedDevices/Fleet.java, examples/java/src/main/java/com/twilio/rest/versionless/deployedDevices/FleetCreator.java, examples/java/src/main/java/com/twilio/rest/versionless/understand/Assistant.java, src/main/resources/twilio-java/api.mustache, src/main/resources/twilio-java/creator.mustache, src/main/resources/twilio-java/models.mustache, src/main/resources/twilio-java/updater.mustache
=> chore: added imports

src/main/java/com/twilio/oai/api/JavaApiResourceBuilder.java, src/main/java/com/twilio/oai/common/ApplicationConstants.java
filtered non success responses
=> chore: filtered non success responses

src/main/java/com/twilio/oai/api/JavaApiResourceBuilder.java
added support for list response.
=> Support list response

src/main/java/com/twilio/oai/TwilioTerraformGenerator.java
Prevents Terraform build from failing when SID is passed in query params instead of path params
=> fix: Check empty pathParam in Terraform

src/main/java/com/twilio/oai/TwilioTerraformGenerator.java, src/main/resources/terraform-provider-twilio/api.mustache
=> fix: Fetch operation with queryParams in Terraform

examples/spec/twilio_api_v2010.yaml, src/main/java/com/twilio/oai/api/RubyApiResourceBuilder.java
Changes made in reader of dependentProperties in accordance to 
https://code.hq.twilio.com/twilio/yps/pull/169/files
=> chore: updated reader for dependentProperties

examples/python/Dockerfile
Python tests were failing due to an issue in building wheels for aiohttp in python:latest. So modified the dockerfile to test on python:3.11
=> fix: running tests on python:3.11 instead of python:latest

examples/java/src/main/java/com/twilio/rest/api/v2010/AccountCreator.java, examples/java/src/main/java/com/twilio/rest/api/v2010/AccountDeleter.java, examples/java/src/main/java/com/twilio/rest/api/v2010/AccountFetcher.java, examples/java/src/main/java/com/twilio/rest/api/v2010/AccountReader.java, examples/java/src/main/java/com/twilio/rest/api/v2010/AccountUpdater.java, examples/java/src/main/java/com/twilio/rest/api/v2010/account/CallCreator.java, examples/java/src/main/java/com/twilio/rest/api/v2010/account/CallDeleter.java, examples/java/src/main/java/com/twilio/rest/api/v2010/account/CallFetcher.java, examples/java/src/main/java/com/twilio/rest/api/v2010/account/call/FeedbackCallSummaryUpdater.java, examples/java/src/main/java/com/twilio/rest/flexapi/v1/CallUpdater.java, examples/java/src/main/java/com/twilio/rest/flexapi/v1/credential/AwsDeleter.java, examples/java/src/main/java/com/twilio/rest/flexapi/v1/credential/AwsFetcher.java, examples/java/src/main/java/com/twilio/rest/flexapi/v1/credential/AwsReader.java, examples/java/src/main/java/com/twilio/rest/flexapi/v1/credential/AwsUpdater.java, examples/java/src/main/java/com/twilio/rest/flexapi/v1/credential/NewCredentialsCreator.java, examples/java/src/main/java/com/twilio/rest/flexapi/v1/credential/aws/HistoryFetcher.java, examples/java/src/main/java/com/twilio/rest/versionless/deployedDevices/FleetCreator.java, examples/java/src/main/java/com/twilio/rest/versionless/deployedDevices/FleetFetcher.java, examples/java/src/main/java/com/twilio/rest/versionless/understand/AssistantReader.java, examples/python/Dockerfile, src/main/java/com/twilio/oai/api/JavaApiResourceBuilder.java, src/main/resources/twilio-java/creator.mustache, src/main/resources/twilio-java/deleter.mustache, src/main/resources/twilio-java/fetcher.mustache, src/main/resources/twilio-java/reader.mustache, src/main/resources/twilio-java/updater.mustache
=> chore: sync with main

src/main/java/com/twilio/oai/api/ApiResourceBuilder.java, src/main/java/com/twilio/oai/api/JavaApiResourceBuilder.java, src/main/resources/twilio-java/models.mustache
1. Previously json naming for variables were snake case which is not correct. It has been changed to baseName which is same as defined in open-api specs.
2.  Corrected the usage on how to identify if and operation has content type as application/json.
=> corrected model json name and hasNestedRequestBody

examples/go/go-client/helper/rest/api/v2010/accounts.go, src/main/resources/twilio-go/api.mustache, src/main/resources/twilio-go/partial_serialization.mustache
https://issues.corp.twilio.com/browse/DII-1245
Generator changes for go json ingress support
=> feat: Generator changes for go json ingress support

examples/go/Dockerfile, examples/go/go-client/go.mod
=> fix: Adding sleep since go test cases are running before mock server is up

scripts/build_twilio_library.py
Temporary Special handling for domains without version
=> fix: Temporary Special handling for domains without version

src/main/java/com/twilio/oai/TwilioGoGenerator.java, src/main/resources/twilio-go/api.mustache
Implements allOf feature for go language. Go language implements models for responses. allOf feature implementation requires creation of new models with the properties mentioned in the allOf schema. This has to be referred going forward in the method signatures. This PR also fixes the bug in api.mustache file where last is referred instead of -last
=> feat: Implementing allOf feature for go

src/main/java/com/twilio/oai/CodegenUtils.java, src/main/java/com/twilio/oai/api/CsharpApiResourceBuilder.java, src/main/java/com/twilio/oai/resolver/csharp/CsharpCodegenModelDataTypeResolver.java, src/main/resources/twilio-csharp/models.mustache
**1. C# Enum fix**
- Previously in C# Enums is processed if it contains "Enum" constant in its name, it has been modified and now CodegenUtils.isPropertySchemaEnum(property) is used.
**2. Response Model variable naming fix**
- In c# response models are defined at same level where models are defined and variables names starts with capital letter.
So it is creating conflict. for example: 
If a model is used in response model, it defined as
class definition --> public class **Types** { ... }
response model ---> public Types **Types**
Above was creating conflict, thus response model variable name is renamed to _Types.
=> chore: corrected enum and response model variable naming in c#

src/main/java/com/twilio/oai/resolver/python/PythonCodegenModelDataTypeResolver.java
There were some Enum objects that did not have 'enum' word in their datatype or anywhere else. See [here](https://github.com/twilio/twilio-oai/blob/2.0.0-rc-safe/spec/yaml/twilio_content_sdk.yaml#L75). But they also need to be resolved the same way. So added a check for that.
=> chore: resolved enum values without "Enum" in name

src/main/resources/twilio-python/listOperations.handlebars
=> chore: fixed python query param

src/main/java/com/twilio/oai/TwilioCodegenAdapter.java, src/main/java/com/twilio/oai/TwilioJavaGenerator.java, src/main/java/com/twilio/oai/resolver/java/JavaConventionResolver.java
read version from file name, fix server url pattern, fix parameter enum datatype
=> chore: read version from file name, fix server url pattern, fix enum

src/main/resources/twilio-python/listOperations.handlebars
Handling cases when there are more than one query or header params
=> fix: python support for multiple query and header params

scripts/prism.sh
Since April 2, 2024 GitHub deprecated Docker compose v1. Complete issue can be found [here](https://github.com/orgs/community/discussions/116610). Following this [migration guide](https://docs.docker.com/compose/migrate/). 
=> chore: migrating to docker compose v2

examples/go/go-client/helper/rest/flex/v1/README.md, examples/go/go-client/helper/rest/flex/v1/model_update_call_response.go, examples/go/go-client/helper/rest/flex/v1/voice.go, src/main/java/com/twilio/oai/TwilioGoGenerator.java, src/main/resources/twilio-go/api_service.mustache
Changes for Go json ingress. The impact can be seen [here](https://github.com/twilio/twilio-go/pull/242). 
=> fix: fixes for go json ingress 

examples/java/src/main/java/com/twilio/rest/api/v2010/Account.java, examples/java/src/main/java/com/twilio/rest/api/v2010/account/Call.java, examples/java/src/main/java/com/twilio/rest/api/v2010/account/call/FeedbackCallSummary.java, examples/java/src/main/java/com/twilio/rest/flexapi/v1/Call.java, examples/java/src/main/java/com/twilio/rest/flexapi/v1/credential/Aws.java, examples/java/src/main/java/com/twilio/rest/flexapi/v1/credential/NewCredentials.java, examples/java/src/main/java/com/twilio/rest/flexapi/v1/credential/aws/History.java, examples/java/src/main/java/com/twilio/rest/versionless/deployedDevices/Fleet.java, examples/java/src/main/java/com/twilio/rest/versionless/understand/Assistant.java, src/main/java/com/twilio/oai/api/JavaApiResourceBuilder.java, src/main/resources/twilio-java/responseModel.mustache
Adding fix: Process enum if it is present as a parameter.
Display enum only from enums only. Avoid displaying enum from response model as it might add duplicate enums.
Corresponding twilio-java code:
https://github.com/twilio/twilio-java/pull/795
Adding variant class PR: https://github.com/twilio/twilio-java/pull/796
=> fix: added enum support in parameters

examples/csharp/Dockerfile
Upgrading dotnet-sonarscanner to latest version
=> chore: upgrade dotnet-sonarscanner version

src/main/resources/twilio-python/listOperations.handlebars
Correcting application/json header in python
=> fix: corrected header in python

src/main/java/com/twilio/oai/CodegenUtils.java, src/main/resources/twilio-python/modelClasses.handlebars
Earlier in case of Enums inside nested classes, the enums were treated as class. This fix makes sure .to_dict() is added only when the object is no way an enum.
=> fix: handling nested enum correctly in python

src/test/java/com/twilio/oai/TwilioGeneratorTest.java
=> chore: remove local file paths

scripts/build_twilio_library.py
Skipping monitor/v2 spec file due to difference in response schema for same resource (Alarms)
=> chore: skip monitor v2 in sdk generation

scripts/build_twilio_library.py
=> fix: Update build_twilio_library.py

src/main/java/com/twilio/oai/TwilioPhpGenerator.java, src/main/java/com/twilio/oai/resolver/php/PhpPropertyResolver.java, src/main/java/com/twilio/oai/templating/mustache/TitleCamelCaseLambda.java, src/main/resources/twilio-php/instance.mustache, src/main/resources/twilio-php/models/modelClass.mustache
Removing overwriting of baseName in PHP to process response model correctly
=> chore: fixed baseName error in PHP

src/main/resources/twilio-php/models/modelClass.mustache
Extension of #629 by correcting json serialize function as well
=> chore: using correct baseName in json serialize in php

examples/java/unit-test/rest/TwilioRestTest.java
Java tests started failing due to update in [joda-time](https://github.com/JodaOrg/joda-time/pull/805) library. Updated the same. 
=> chore: fix java test

.github/workflows/test.yml, src/main/java/com/twilio/oai/TwilioGoGenerator.java, src/main/resources/twilio-go/api.mustache
=> chore: go fix for PageSize parameter

examples/php/src/Twilio/Rest/FlexApi/V1/Credential/NewCredentialsList.php, src/main/java/com/twilio/oai/common/ApplicationConstants.java, src/main/java/com/twilio/oai/resolver/php/PhpParameterResolver.java
=> chore: php object array fix

examples/php/src/Twilio/Rest/Api/V2010/Account/Call/FeedbackCallSummaryContext.php, examples/php/src/Twilio/Rest/Api/V2010/Account/CallContext.php, examples/php/src/Twilio/Rest/Api/V2010/Account/CallList.php, examples/php/src/Twilio/Rest/Api/V2010/AccountContext.php, examples/php/src/Twilio/Rest/Api/V2010/AccountList.php, examples/php/src/Twilio/Rest/FlexApi/V1/CallContext.php, examples/php/src/Twilio/Rest/FlexApi/V1/Credential/Aws/HistoryContext.php, examples/php/src/Twilio/Rest/FlexApi/V1/Credential/AwsContext.php, examples/php/src/Twilio/Rest/FlexApi/V1/Credential/AwsList.php, examples/php/src/Twilio/Rest/FlexApi/V1/Credential/NewCredentialsList.php, examples/php/src/Twilio/Rest/Versionless/DeployedDevices/FleetContext.php, examples/php/src/Twilio/Rest/Versionless/DeployedDevices/FleetList.php, examples/php/src/Twilio/Rest/Versionless/Understand/AssistantList.php, scripts/build_twilio_library.py, src/main/java/com/twilio/oai/api/PhpApiResourceBuilder.java, src/main/resources/twilio-php/contextMethod.mustache, src/main/resources/twilio-php/listRead.mustache
1. Added php to generate versionless endpionts for orgs API
2. Handle Content-Type header and Accept header in php using `consumes` and `produces` property
3. Skip adding accept header in case of delete operation
4. Add support for query params other than pagination ones in list operations (till now it was only supported is there were at least two query params, but an exception to this is this [endpoint](https://github.com/twilio/twilio-oai/blob/9f3a66723b7ec0a2c96c2a45df742a6e8cd95e7b/spec/json/twilio_iam_organizations.json#L74))
=> chore: changes for php oauth

scripts/build_twilio_library.py, scripts/process_orgs_api.py
Change file name in case of go language
=> chore: Go orgs API

examples/csharp/src/Twilio/Rest/Api/V2010/AccountResource.cs, examples/go/go-client/helper/rest/api/v2010/README.md, examples/go/go-client/helper/rest/api/v2010/accounts.go, examples/java/src/main/java/com/twilio/rest/api/v2010/Account.java, examples/node/src/rest/api/v2010/account.ts, examples/node/src/rest/api/v2010/account/call.ts, examples/node/src/rest/api/v2010/account/call/feedbackCallSummary.ts, examples/php/src/Twilio/Rest/Api/V2010/AccountInstance.php, examples/python/twilio/rest/api/v2010/account/__init__.py, examples/python/twilio/rest/api/v2010/account/call/__init__.py, examples/python/twilio/rest/api/v2010/account/call/feedback_call_summary.py, examples/ruby/lib/twilio-ruby/rest/api/v2010/account.rb, examples/ruby/lib/twilio-ruby/rest/api/v2010/account/call.rb, examples/ruby/lib/twilio-ruby/rest/api/v2010/account/call/feedback_call_summary.rb, examples/ruby/lib/twilio-ruby/rest/flex_api/v1/credential/aws.rb, examples/ruby/lib/twilio-ruby/rest/flex_api/v1/credential/aws/history.rb, examples/ruby/lib/twilio-ruby/rest/flex_api/v1/credential/new_credentials.rb, examples/ruby/lib/twilio-ruby/rest/preview_iam/v1/authorize.rb, examples/ruby/lib/twilio-ruby/rest/preview_iam/v1/token.rb, examples/ruby/lib/twilio-ruby/rest/versionless/deployed_devices/fleet.rb, examples/spec/twilio_api_v2010.yaml, src/main/java/com/twilio/oai/api/PhpApiResourceBuilder.java
PHP has a bug that when we merge response models with similar properties, the union of the properties is not correct and it leads to duplicate properties, see [here](https://github.com/twilio/twilio-php/blob/a68a13ed8ddc720d5adb580cbc22b4fd80dc6b38/src/Twilio/Rest/Assistants/V1/AssistantInstance.php#L31-L54). This is due to the current PHP design which adds the distinct models repetitively in the same apiResponseModel which is not a set and thus duplicates penetrate.
=> fix: resolve php duplicate model properties correctly

examples/csharp/src/Twilio/Rest/PreviewIam/Organizations/UserResource.cs, src/main/resources/twilio-csharp/resource/GeneratePath.mustache
Twilio csharp is capitalising the first character of path param.
https://github.com/twilio/twilio-csharp/issues/782
=> fix: Twilio csharp path param

src/main/java/com/twilio/oai/resolver/java/JavaConventionResolver.java
Enum handling in java json request body throws null pointer exception.
Preview PR - https://github.com/twilio/twilio-java/pull/865
=> chore: enum handling in request body in java

examples/java/src/main/java/com/twilio/rest/flexapi/v1/credential/NewCredentialsCreator.java, src/main/java/com/twilio/oai/api/JavaApiResourceBuilder.java, src/main/resources/twilio-java/postParams.mustache
In case of list of objects, we need to serialize using objectToJson()
Preview changes - https://github.com/twilio/twilio-java/pull/874
=> chore: handle list of objects

src/main/java/com/twilio/oai/TwilioJavaGeneratorModern.java, src/main/java/com/twilio/oai/java/JavaApiResourceBuilder.java, src/main/java/com/twilio/oai/java/processor/JavaOperationProcessor.java
Created operation processor and injected in api resource builder.
=> created operation processor

src/main/java/com/twilio/oai/api/CsharpApiResourceBuilder.java, src/main/java/com/twilio/oai/common/EnumConstants.java
C# currently has PATCH method added in [helper](https://github.com/twilio/twilio-csharp/blob/42457f6e921a2b04cb102a4f445542a9ea984251/src/Twilio/Http/HttpMethod.cs#L21), but not in oai-generator. This PR adds PATCH method in oai-generator
=> chore: add patch method in C#

examples/node/src/rest/previewIam/versionless/organization/roleAssignment.ts, src/main/resources/twilio-node/model.mustache
Nested var name in node was coming in wrong casing due to baseName. Using name now.
=> chore: handle name of var correctly in nested json for node
