twilio/twilio-oai-generator

- .gitignore
- README.md
- examples/build_twilio_go.py
This makes the paths less verbose and redundant.
Relates to https://github.com/twilio/twilio-go/pull/73
> chore: move contents of 'twilio' folder to the top-level

- examples/go/test/unit_test.go
- src/main/resources/twilio-go/api.mustache
> fix: array type template

- src/main/java/com/twilio/oai/TwilioTerraformGenerator.java
Fixes names such as `integration.channel`, `integration.url` in the terraform provider resources
Related PR: https://github.com/twilio/terraform-provider-twilio/pull/31
> fix resource property names in terraform provider

- pom.xml
- src/main/java/com/twilio/oai/TwilioTerraformGenerator.java
- src/main/resources/terraform-provider-twilio/api.mustache
https://github.com/twilio/terraform-provider-twilio/pull/34
> fix: convert sid_key ints into strings

- src/main/java/com/twilio/oai/TwilioTerraformGenerator.java
In certain cases such as chat service, the [create](https://www.twilio.com/docs/chat/rest/service-resource#create-a-service-resource) takes in only one parameter but we cannot assume all the response parameters are "computed" since they can be updated. 
Related PR: https://github.com/twilio/terraform-provider-twilio/pull/35
> fix: Update "SchemaComputed" to "SchemaOptional"

- src/main/java/com/twilio/oai/TwilioTerraformGenerator.java
- src/main/resources/terraform-provider-twilio/api.mustache
This allows resources with additional update parameters to be created and updated in a single `terraform apply`.
https://github.com/twilio/terraform-provider-twilio/pull/39
> fix: update certain resources after creating them

- src/main/java/com/twilio/oai/TwilioTerraformGenerator.java
- src/main/resources/terraform-provider-twilio/api.mustache
Response properties cannot be changed unless they are part of the create/update properties, so we'll only include create/update properties.
https://github.com/twilio/terraform-provider-twilio/pull/40
> fix: replace response properties with update properties

- examples/go/test/api_test.go
- examples/go/test/unit_test.go
- src/main/java/com/twilio/oai/AbstractTwilioGoGenerator.java
- src/main/java/com/twilio/oai/TwilioTerraformGenerator.java
Use `int` instead of `int32` for integer types
Related PRs:
https://github.com/twilio/twilio-go/pull/86
https://github.com/twilio/terraform-provider-twilio/pull/44
> chore: use primitive int for integer types

- Makefile
- pom.xml
Use the [latest openapi-generator](https://github.com/OpenAPITools/openapi-generator/releases/tag/v5.2.0)
> chore: upgrade openapi-generator to version 5.2.0

- .gitignore
- examples/terraform/unit/accounts_calls_recordings_test.go
- examples/terraform/unit/credentials_aws_test.go
- examples/terraform/unit/serverless_services_environments_test.go
- examples/twilio_api_v2010.yaml
- src/main/java/com/twilio/oai/TwilioTerraformGenerator.java
- src/test/java/com/twilio/oai/TwilioTerraformGeneratorTest.java
Adds API response fields that cannot be used as operation parameters as "Computed" Terraform Resource schema fields.
Related PR:
https://github.com/twilio/terraform-provider-twilio/pull/71
> fix: add computed terraform resource properties

- examples/build_twilio_go.py
It's too verbose and beggy. We'll just print the directory we're writing.
> chore: suppress stdout when generating libraries

- Makefile
- pom.xml
- src/main/java/com/twilio/oai/AbstractTwilioGoGenerator.java
- src/main/resources/twilio-go/partial_serialization.mustache
Extracts minimal code needed from upstream `postProcessOperationsWithModels` to avoid NPE when generating sample values. Also fixes serialization template for arrays to depend on type of the inner items.
Relates to https://github.com/OpenAPITools/openapi-generator/issues/11470
> chore: upgrade openapi-generator to version 5.3.1

- Makefile
- pom.xml
No changes to twilio-go or terraform-provider-twilio.
> chore: upgrade openapi-generator to version 5.4.0

- examples/go-client/Dockerfile
- examples/go-client/helper/rest/api/v2010/accounts_calls.go
- examples/go-client/helper/rest/api/v2010/accounts_calls_recordings.go
- examples/go-client/helper/rest/api/v2010/credentials_aws.go
- examples/go-client/helper/rest/api/v2010/unit_test.go
- src/main/resources/twilio-go/api.mustache
Fixes bugs where limit param was not always enforced and empty results caused an error when attempting to fetch next page.
Relates to https://github.com/twilio/twilio-go/pull/148
> fix: refactor limit enforcement and fetching next page

- examples/go/go-client/helper/rest/api/v2010/README.md
- examples/go/go-client/helper/rest/api/v2010/api_test.go
- examples/go/go-client/helper/rest/api/v2010/model_test_response_object.go
- examples/java/src/main/java/com/twilio/rest/api/v2010/Account.java
- examples/java/src/main/java/com/twilio/rest/api/v2010/account/Call.java
- examples/java/src/main/java/com/twilio/rest/api/v2010/account/call/FeedbackCallSummary.java
- examples/java/src/main/java/com/twilio/rest/api/v2010/credential/Aws.java
- examples/java/src/main/java/com/twilio/rest/api/v2010/credential/NewCredentials.java
- examples/java/src/main/java/com/twilio/rest/api/v2010/credential/NewCredentialsCreator.java
- examples/java/unit-test/rest/TwilioRestTest.java
- examples/node/lib/rest/api/v2010/accounts.ts
- examples/node/lib/rest/api/v2010/accounts/calls.ts
- examples/node/lib/rest/api/v2010/accounts/calls/feedbackSummary.ts
- examples/node/lib/rest/api/v2010/credentials/aWS.ts
- examples/twilio_api_v2010.yaml
- src/main/java/com/twilio/oai/AbstractTwilioGoGenerator.java
- src/main/java/com/twilio/oai/TwilioGoGenerator.java
- src/test/java/com/twilio/oai/TwilioGeneratorTest.java
Added support to parse enum changes added in OAI spec for go as part of the PR: https://github.com/twilio/twilio-oai/pull/71
updated to spec file for related enum changes
> fix: go enum schema changes

- examples/go/go-client/helper/rest/api/v2010/api_test.go
- examples/prism/docker-compose.yml
- prism.sh
Seeing a regression in prism where an operation with required body params was not being rejected when no body was present. Updated to sending one of the required params but not both.
Relates to https://github.com/stoplightio/prism/pull/2103
> test: refactor the required body param test to fix regression in prism

- examples/node/lib/rest/api/v2010/account/call.ts
- examples/node/spec/unit/account/call.spec.ts
- src/main/resources/twilio-node/api-single.mustache
All other path params come from the parent container.
> fix: update node getter functions to only require last path param

- examples/node/lib/rest/api/V2010.ts
- examples/node/lib/rest/api/v2010/account.ts
- examples/node/lib/rest/api/v2010/account/call.ts
- examples/node/lib/rest/api/v2010/account/call/feedbackCallSummary.ts
- examples/node/lib/rest/flexApi/v1/call.ts
- examples/node/lib/rest/flexApi/v1/credential.ts
- examples/node/lib/rest/flexApi/v1/credential/aws.ts
- examples/node/lib/rest/flexApi/v1/credential/newCredentials.ts
- examples/node/lib/rest/versionless/deployed_devices/fleet.ts
- examples/node/lib/rest/versionless/understand/assistant.ts
- src/main/java/com/twilio/oai/TwilioNodeGenerator.java
- src/main/resources/twilio-node/api-single.mustache
- src/main/resources/twilio-node/pagination.mustache
- src/main/resources/twilio-node/responseModel.mustache
Two main changes here:
1. Pagination now only gets generated when the resource has a list operation
2. *Instance and *Solution are now generated for all api files
[Internal Link](https://issues.corp.twilio.com/browse/DI-2368)
> fix: Only generate pagination when necessary for Node

- src/main/java/com/twilio/oai/PathUtils.java
- src/test/java/com/twilio/oai/PathUtilsTest.java
Some pre-work to DI-2348.
Adding these tests for two main reasons:
1. These methods get used a lot and can easily cause issues on edge cases
2. It makes it easier to decipher what a regex is doing by having examples
> test: Add regex tests

- examples/spec/twilio_api_v2010.yaml
- src/main/java/com/twilio/oai/PathUtils.java
- src/main/java/com/twilio/oai/resource/Resource.java
- src/test/java/com/twilio/oai/PathUtilsTest.java
https://github.com/twilio/twilio-node/pull/820
> fix: use proper parent resource when prefix not matched in node-oai

- .github/workflows/test.yml
Fixes warning:
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
> chore: upgrade GitHub Actions dependencies

- examples/spec/twilio_api_v2010.yaml
- src/main/java/com/twilio/oai/AbstractTwilioGoGenerator.java
- src/main/java/com/twilio/oai/DirectoryStructureService.java
We use our own set of tags for creating the nested directory structure. We don't want any other tags to exist.
> feat: clear operation tags during pre-processing

- examples/go/go-client/terraform/resources/flex/v1/README.md
- examples/go/go-client/terraform/resources/flex/v1/api_default.go
- src/main/java/com/twilio/oai/StringHelper.java
- src/main/java/com/twilio/oai/TwilioTerraformGenerator.java
- src/main/java/com/twilio/oai/resolver/java/JavaConventionResolver.java
- src/test/java/com/twilio/oai/StringHelperTest.java
Also fixes issue where things like `callbackURL` were turning to `callback_u_r_l` in underlying DefaultCodegen.
> chore: consolidate snake_case logic

- .github/workflows/test.yml
- Makefile
- examples/csharp/Dockerfile
- examples/csharp/integrationTest/Rest/ApiIntegrationTest.cs
- examples/csharp/test.sh
- examples/prism/docker-compose.yml
- scripts/prism.sh
[DII-747](https://issues.corp.twilio.com/browse/DII-747) Exclude csharp from sonar analysis from github actions and run from scripts
Exclude csharp from sonar analysis from github actions and run from scripts. Also integration tests are failing since the argument to create call in call resource was given incorrect in integration tests
> Csharp sonar fixes

- examples/php/Dockerfile
- src/main/java/com/twilio/oai/api/JavaApiResourceBuilder.java
updating the version for xdebug library to 2.9.0. Discussion here https://github.com/flyve-mdm/docker-environment/issues/68
> fix: updating xdebug version

- examples/php/sonar-project.properties
- examples/php/src/Twilio/Rest/Api/V2010/Account/CallContext.php
- examples/php/src/Twilio/Rest/Api/V2010/Account/CallList.php
- src/main/java/com/twilio/oai/TwilioPhpGenerator.java
- src/main/java/com/twilio/oai/api/PhpApiResourceBuilder.java
- src/main/resources/twilio-php/context.mustache
- src/main/resources/twilio-php/list.mustache
- src/main/resources/twilio-php/magicGetterandCaller.mustache
- Since PHP < 8.0  doesn't support folder name to be similar to an existing Keyword, hence needed to modify the Function folder name to be TwilioFunction as is in twilio-php.
- set correct property and method annotations
- exclude domain and client files from sonar coverage
> fix: build issues

- examples/csharp/src/Twilio/Rest/FlexApi/V1/CallResource.cs
- examples/go/go-client/helper/rest/flex/v1/model_update_call_200_response.go
- examples/java/src/main/java/com/twilio/rest/flexapi/v1/Call.java
- examples/java/unit-test/rest/TwilioRestTest.java
- examples/node/lib/rest/flexApi/v1/call.ts
- examples/php/src/Twilio/Rest/FlexApi/V1/CallInstance.php
- examples/spec/twilio_flex_v1.yaml
- src/main/java/com/twilio/oai/TwilioGoGenerator.java
- src/main/java/com/twilio/oai/TwilioTerraformGenerator.java
- src/main/java/com/twilio/oai/api/FluentApiResourceBuilder.java
- src/main/java/com/twilio/oai/api/JavaApiResourceBuilder.java
- src/main/java/com/twilio/oai/common/ApplicationConstants.java
- src/main/java/com/twilio/oai/resolver/php/PhpParameterResolver.java
- src/main/java/com/twilio/oai/resolver/php/PhpPropertyResolver.java
- src/main/resources/twilio-node/responseModel.mustache
This removes TypeScript errors for non-matching types.
https://github.com/twilio/twilio-node/pull/854
> fix: add stringify extension for non-string path param response properties

- examples/node/lib/rest/api/v2010/account.ts
- examples/node/lib/rest/api/v2010/account/call/feedbackCallSummary.ts
- src/main/resources/twilio-node/api-single.mustache
https://github.com/twilio/twilio-node/pull/876
> fix: don't support callback as first arg when params are required in node

- src/main/java/com/twilio/oai/template/AbstractApiActionTemplate.java
Node examples are currently broken. This fixes it.
> fix: refactor API filename generation for ruby

- examples/ruby/lib/twilio-ruby/rest/api/v2010/account.rb
- examples/ruby/lib/twilio-ruby/rest/api/v2010/account/call.rb
- examples/ruby/lib/twilio-ruby/rest/api/v2010/account/call/feedback_call_summary.rb
- examples/ruby/lib/twilio-ruby/rest/flex_api/v1/call.rb
- examples/ruby/lib/twilio-ruby/rest/flex_api/v1/credential.rb
- examples/ruby/lib/twilio-ruby/rest/flex_api/v1/credential/aws.rb
- examples/ruby/lib/twilio-ruby/rest/flex_api/v1/credential/aws/history.rb
- examples/ruby/lib/twilio-ruby/rest/flex_api/v1/credential/new_credentials.rb
- examples/ruby/lib/twilio-ruby/rest/versionless/deployed_devices/fleet.rb
- examples/ruby/lib/twilio-ruby/rest/versionless/understand/assistant.rb
- src/main/resources/twilio-ruby/api.mustache
- src/main/resources/twilio-ruby/page.mustache
> chore: Ruby add Page template

- examples/php/src/Twilio/Rest/Api/V2010/Account/Call/FeedbackCallSummaryContext.php
- examples/php/src/Twilio/Rest/Api/V2010/Account/Call/FeedbackCallSummaryList.php
- examples/php/src/Twilio/Rest/Api/V2010/Account/Call/FeedbackCallSummaryOptions.php
- examples/php/src/Twilio/Rest/Api/V2010/Account/CallContext.php
- examples/php/src/Twilio/Rest/Api/V2010/Account/CallList.php
- examples/php/src/Twilio/Rest/Api/V2010/Account/CallOptions.php
- examples/php/src/Twilio/Rest/Api/V2010/AccountContext.php
- examples/php/src/Twilio/Rest/Api/V2010/AccountList.php
- examples/php/src/Twilio/Rest/Api/V2010/AccountOptions.php
- examples/php/src/Twilio/Rest/FlexApi/V1/CallContext.php
- examples/php/src/Twilio/Rest/FlexApi/V1/CallList.php
- examples/php/src/Twilio/Rest/FlexApi/V1/Credential/Aws/HistoryContext.php
- examples/php/src/Twilio/Rest/FlexApi/V1/Credential/Aws/HistoryList.php
- examples/php/src/Twilio/Rest/FlexApi/V1/Credential/Aws/HistoryOptions.php
- examples/php/src/Twilio/Rest/FlexApi/V1/Credential/AwsContext.php
- examples/php/src/Twilio/Rest/FlexApi/V1/Credential/AwsList.php
- examples/php/src/Twilio/Rest/FlexApi/V1/Credential/AwsOptions.php
- examples/php/src/Twilio/Rest/FlexApi/V1/Credential/NewCredentialsList.php
- examples/php/src/Twilio/Rest/FlexApi/V1/Credential/NewCredentialsOptions.php
- examples/php/src/Twilio/Rest/FlexApi/V1/CredentialList.php
- examples/php/src/Twilio/Rest/Versionless/DeployedDevices/FleetContext.php
- examples/php/src/Twilio/Rest/Versionless/DeployedDevices/FleetList.php
- examples/php/src/Twilio/Rest/Versionless/DeployedDevices/FleetOptions.php
- examples/php/src/Twilio/Rest/Versionless/Understand/AssistantList.php
- src/main/resources/twilio-php/context.mustache
- src/main/resources/twilio-php/contextMethod.mustache
- src/main/resources/twilio-php/list.mustache
- src/main/resources/twilio-php/options/optionsClass.mustache
Removed the trailing comma within the function call.
Correct alignment of braces.
Cluster Tests successful run: [here](https://github.com/twilio/twilio-php/actions/runs/4014524180)
> fix: trailing comma

- src/main/java/com/twilio/oai/AbstractTwilioGoGenerator.java
- src/main/java/com/twilio/oai/TwilioTerraformGenerator.java
- src/main/java/com/twilio/oai/api/PhpDomainBuilder.java
- src/main/java/com/twilio/oai/resolver/csharp/OperationStore.java
When multi-threading, we can no longer exit mid-generation or rely on writable global statics.
> chore: prep for multi-threaded/batch execution

- Makefile
- pom.xml
- scripts/build_twilio_library.py
- scripts/generate.sh
This allows for the version to be specified in 1 place and simplifies the generation command.
> chore: refactor dependency on openapi-generator-cli

- src/main/java/com/twilio/oai/api/FluentApiResourceBuilder.java
- src/main/resources/twilio-python/instance.handlebars
https://github.com/twilio/twilio-python/pull/673
> fix: use the model name for python instance path variables

- src/main/resources/twilio-python/api-single.mustache
https://github.com/twilio/twilio-python/pull/682
> fix: only include list operations if a path is present in python

- examples/python/twilio/rest/api/v2010/account/__init__.py
- examples/python/twilio/rest/api/v2010/account/call/__init__.py
- examples/python/twilio/rest/api/v2010/account/call/feedback_call_summary.py
- examples/python/twilio/rest/flex_api/v1/call.py
- examples/python/twilio/rest/flex_api/v1/credential/aws/__init__.py
- examples/python/twilio/rest/flex_api/v1/credential/aws/history.py
- examples/python/twilio/rest/flex_api/v1/credential/new_credentials.py
- examples/python/twilio/rest/versionless/deployed_devices/fleet.py
- examples/python/twilio/rest/versionless/understand/assistant.py
- src/main/resources/twilio-python/api-single.mustache
Needed for future work where list methods are typed with instance and context types which must already be defined.
https://github.com/twilio/twilio-python/pull/689
> chore: move list implementations to the bottom for python

- scripts/build_twilio_library.py
Fixes issue when generating multiple languages in parallel.
> fix: use language-specific paths for batch generation

- examples/python/twilio/rest/api/v2010/account/__init__.py
- examples/python/twilio/rest/api/v2010/account/call/__init__.py
- examples/python/twilio/rest/api/v2010/account/call/feedback_call_summary.py
- examples/python/twilio/rest/flex_api/v1/credential/new_credentials.py
- src/main/java/com/twilio/oai/TwilioPythonGenerator.java
- src/main/java/com/twilio/oai/api/PythonApiResourceBuilder.java
- src/main/resources/twilio-python/api-single.mustache
This is to match existing behavior since we don’t deserialize into the complex types.
Also fix the List typing.
https://github.com/twilio/twilio-python/pull/691
> fix: use ‘str’ for non-enum complex response properties in python

- examples/csharp/src/Twilio/Rest/Api/V2010/Account/Call/FeedbackCallSummaryOptions.cs
- examples/csharp/src/Twilio/Rest/Api/V2010/Account/Call/FeedbackCallSummaryResource.cs
- examples/csharp/src/Twilio/Rest/Api/V2010/Account/CallOptions.cs
- examples/csharp/src/Twilio/Rest/Api/V2010/Account/CallResource.cs
- examples/csharp/src/Twilio/Rest/Api/V2010/AccountOptions.cs
- examples/csharp/src/Twilio/Rest/Api/V2010/AccountResource.cs
- examples/csharp/src/Twilio/Rest/FlexApi/V1/CallOptions.cs
- examples/csharp/src/Twilio/Rest/FlexApi/V1/CallResource.cs
- examples/csharp/src/Twilio/Rest/FlexApi/V1/Credential/Aws/HistoryOptions.cs
- examples/csharp/src/Twilio/Rest/FlexApi/V1/Credential/Aws/HistoryResource.cs
- examples/csharp/src/Twilio/Rest/FlexApi/V1/Credential/AwsOptions.cs
- examples/csharp/src/Twilio/Rest/FlexApi/V1/Credential/AwsResource.cs
- examples/csharp/src/Twilio/Rest/FlexApi/V1/Credential/NewCredentialsOptions.cs
- examples/csharp/src/Twilio/Rest/FlexApi/V1/Credential/NewCredentialsResource.cs
- examples/csharp/src/Twilio/Rest/Versionless/DeployedDevices/FleetOptions.cs
- examples/csharp/src/Twilio/Rest/Versionless/DeployedDevices/FleetResource.cs
- examples/csharp/src/Twilio/Rest/Versionless/Understand/AssistantOptions.cs
- examples/csharp/src/Twilio/Rest/Versionless/Understand/AssistantResource.cs
- src/main/resources/twilio-csharp/ResourceUsings.mustache
- src/main/resources/twilio-csharp/options/CreateOptions.mustache
- src/main/resources/twilio-csharp/options/GetBody.mustache
- src/main/resources/twilio-csharp/options/GetParams.mustache
- src/main/resources/twilio-csharp/resource/CreateResource.mustache
- Added GetBody() in Options file
- Added request body and contentType support in mustache files
> fix: Json request body added for csharp

- examples/csharp/src/Twilio/Rest/Api/V2010/Account/Call/FeedbackCallSummaryResource.cs
- examples/csharp/src/Twilio/Rest/Api/V2010/Account/CallResource.cs
- examples/csharp/src/Twilio/Rest/Api/V2010/AccountResource.cs
- examples/csharp/src/Twilio/Rest/FlexApi/V1/CallResource.cs
- examples/csharp/src/Twilio/Rest/FlexApi/V1/Credential/AwsResource.cs
- examples/csharp/src/Twilio/Rest/FlexApi/V1/Credential/NewCredentialsResource.cs
- examples/csharp/src/Twilio/Rest/Versionless/DeployedDevices/FleetResource.cs
- examples/java/src/main/java/com/twilio/rest/api/v2010/AccountDeleter.java
- examples/java/src/main/java/com/twilio/rest/api/v2010/AccountFetcher.java
- examples/java/src/main/java/com/twilio/rest/api/v2010/AccountReader.java
- examples/java/src/main/java/com/twilio/rest/api/v2010/AccountUpdater.java
- examples/java/src/main/java/com/twilio/rest/api/v2010/account/CallDeleter.java
- examples/java/src/main/java/com/twilio/rest/api/v2010/account/CallFetcher.java
- examples/java/src/main/java/com/twilio/rest/api/v2010/account/call/FeedbackCallSummaryUpdater.java
- examples/java/src/main/java/com/twilio/rest/flexapi/v1/CallUpdater.java
- examples/java/src/main/java/com/twilio/rest/flexapi/v1/credential/AwsDeleter.java
- examples/java/src/main/java/com/twilio/rest/flexapi/v1/credential/AwsFetcher.java
- examples/java/src/main/java/com/twilio/rest/flexapi/v1/credential/AwsReader.java
- examples/java/src/main/java/com/twilio/rest/flexapi/v1/credential/AwsUpdater.java
- examples/java/src/main/java/com/twilio/rest/flexapi/v1/credential/aws/HistoryFetcher.java
- examples/java/src/main/java/com/twilio/rest/versionless/deployedDevices/FleetFetcher.java
- examples/java/src/main/java/com/twilio/rest/versionless/understand/AssistantReader.java
- src/main/resources/twilio-csharp/options/UpdateOptions.mustache
- src/main/resources/twilio-csharp/resource/CreateResource.mustache
- src/main/resources/twilio-csharp/resource/UpdateResource.mustache
- src/main/resources/twilio-java/deleter.mustache
- src/main/resources/twilio-java/fetcher.mustache
- src/main/resources/twilio-java/reader.mustache
- src/main/resources/twilio-java/updater.mustache
added json support to c# and java update http method.
> fix: Content type set

- examples/java/src/main/java/com/twilio/rest/api/v2010/AccountDeleter.java
- examples/java/src/main/java/com/twilio/rest/api/v2010/AccountFetcher.java
- examples/java/src/main/java/com/twilio/rest/api/v2010/AccountReader.java
- examples/java/src/main/java/com/twilio/rest/api/v2010/account/CallDeleter.java
- examples/java/src/main/java/com/twilio/rest/api/v2010/account/CallFetcher.java
- examples/java/src/main/java/com/twilio/rest/flexapi/v1/CallUpdater.java
- examples/java/src/main/java/com/twilio/rest/flexapi/v1/credential/AwsDeleter.java
- examples/java/src/main/java/com/twilio/rest/flexapi/v1/credential/AwsFetcher.java
- examples/java/src/main/java/com/twilio/rest/flexapi/v1/credential/AwsReader.java
- examples/java/src/main/java/com/twilio/rest/flexapi/v1/credential/aws/HistoryFetcher.java
- examples/java/src/main/java/com/twilio/rest/versionless/deployedDevices/FleetFetcher.java
- examples/java/src/main/java/com/twilio/rest/versionless/understand/AssistantReader.java
- src/main/resources/twilio-java/creator.mustache
- src/main/resources/twilio-java/deleter.mustache
- src/main/resources/twilio-java/fetcher.mustache
- src/main/resources/twilio-java/reader.mustache
- src/main/resources/twilio-java/updater.mustache
- src/test/java/com/twilio/oai/TwilioGeneratorTest.java
Earlier contentType was set in java only when formParam or bodyParam was present in the operation. However, the check should be about json-type body or else. Corrected the mustache file.
> fix: correctly adding contentType in java

- src/main/resources/twilio-python/modelClasses.handlebars
In python, the instancePathParams were not being used to initialize response models in constructors. So removing those unused params.
> chore: removing unused params from python model constructor

- scripts/build_twilio_library.py
Added a null check for content_v1 file before removing it.
> chore: added a null check for content v1 spec file

- examples/csharp/src/Twilio/Rest/Api/V2010/Account/Call/FeedbackCallSummaryResource.cs
- examples/csharp/src/Twilio/Rest/Api/V2010/Account/CallResource.cs
- examples/csharp/src/Twilio/Rest/Api/V2010/AccountResource.cs
- examples/csharp/src/Twilio/Rest/FlexApi/V1/CallResource.cs
- examples/csharp/src/Twilio/Rest/FlexApi/V1/Credential/Aws/HistoryResource.cs
- examples/csharp/src/Twilio/Rest/FlexApi/V1/Credential/AwsResource.cs
- examples/csharp/src/Twilio/Rest/FlexApi/V1/Credential/NewCredentialsResource.cs
- examples/csharp/src/Twilio/Rest/PreviewIam/Organizations/UserResource.cs
- examples/csharp/src/Twilio/Rest/PreviewIam/V1/TokenResource.cs
- examples/csharp/src/Twilio/Rest/Versionless/DeployedDevices/FleetResource.cs
- examples/csharp/src/Twilio/Rest/Versionless/Understand/AssistantResource.cs
- src/main/java/com/twilio/oai/TwilioCsharpGenerator.java
- src/main/java/com/twilio/oai/api/CsharpApiResources.java
- src/main/resources/twilio-csharp/Pagination.mustache
- src/main/resources/twilio-csharp/ResourceUsings.mustache
- src/main/resources/twilio-csharp/resource/CreateResource.mustache
- src/main/resources/twilio-csharp/resource/DeleteResource.mustache
- src/main/resources/twilio-csharp/resource/FetchResource.mustache
- src/main/resources/twilio-csharp/resource/ReadResource.mustache
- src/main/resources/twilio-csharp/resource/UpdateResource.mustache
Public OAuth changes for twilio-c#
> feat: Public OAuth changes for twilio-c#

- examples/ruby/lib/twilio-ruby/rest/api/v2010/account.rb
- examples/ruby/lib/twilio-ruby/rest/api/v2010/account/call.rb
- examples/ruby/lib/twilio-ruby/rest/flex_api/v1/credential/new_credentials.rb
- src/main/java/com/twilio/oai/DirectoryStructureService.java
- src/main/java/com/twilio/oai/StringHelper.java
- src/main/java/com/twilio/oai/api/RubyApiResourceBuilder.java
This implementation stops using mount_name and uses url to do the mapping
Validation check pipeline: https://buildkite.com/twilio/twilio-librarian-status-checks/builds/11963#_
> bug: ruby to use url instead of mount_name for mapping

- examples/python/twilio/rest/api/v2010/account/__init__.py
- examples/python/twilio/rest/api/v2010/account/call/__init__.py
- examples/python/twilio/rest/flex_api/v1/credential/new_credentials.py
- examples/python/twilio/rest/versionless/deployed_devices/fleet.py
- src/main/resources/twilio-python/context.handlebars
- src/main/resources/twilio-python/listOperations.handlebars
Fixing header parameter issues in twilio-python
> fix: Fixing header parameter issues in twilio-python

- src/main/resources/twilio-php/models/modelClass.mustache
In PHP, the JSON request body params were not resolved correctly. They were to be read from `name` instead of `baseName` since baseName is explicitly being converted to camelCase. Fixing this enable users to access the JSON Payload APIs correctly.
> chore: pass correct param names in request body for php

- src/main/resources/twilio-php/listRead.mustache
Add required query params in read operation for PHP. 
Verified that this issue is only in PHP and not in any other language.
Review PR for php: https://github.com/twilio/twilio-php/pull/842 [Do not merge]
> chore: add required query param in read operations php

- examples/go/go-client/helper/rest/api/v2010/accounts.go
- examples/go/go-client/helper/rest/api/v2010/accounts_calls.go
- examples/go/go-client/helper/rest/api/v2010/accounts_calls_feedback_summary.go
- examples/go/go-client/helper/rest/api/v2010/model_list_account_response.go
- examples/go/go-client/helper/rest/api/v2010/model_list_health_check.go
- examples/go/go-client/helper/rest/api/v2010/model_test_response_object.go
- examples/go/go-client/helper/rest/api/v2010/model_test_response_object_test_array_of_objects.go
- examples/go/go-client/helper/rest/api/v2010/model_test_response_object_test_object.go
- examples/go/go-client/helper/rest/flex/v1/credentials_aws.go
- examples/go/go-client/helper/rest/flex/v1/credentials_aws_history.go
- examples/go/go-client/helper/rest/flex/v1/model_list_credential_aws_response.go
- examples/go/go-client/helper/rest/flex/v1/model_list_credential_aws_response_meta.go
- examples/go/go-client/helper/rest/flex/v1/model_test_response_object.go
- examples/go/go-client/helper/rest/flex/v1/model_update_call_response.go
- examples/go/go-client/helper/rest/flex/v1/voice.go
- examples/go/go-client/terraform/resources/api/v2010/api_default.go
- examples/go/go-client/terraform/resources/flex/v1/api_default.go
- src/main/resources/twilio-go/partial_serialization.mustache
go fix for path params
https://github.com/twilio/twilio-go/pull/263
> chore: go fix for path params

- src/main/java/com/twilio/oai/TwilioJavaGeneratorModern.java
- src/main/java/com/twilio/oai/java/JavaTemplateUpdater.java
- src/main/java/com/twilio/oai/java/format/JavaUpdateDefaultMapping.java
- src/main/java/com/twilio/oai/java/format/OpenApiSpecFormatFeatureConstants.java
added typemapping to convert format to java specific data type and added importmapping for the java datatypes that are mapping to format in open api spec.
> Update schema mapping

- src/main/java/com/twilio/oai/java/format/Deserializer.java
- src/main/java/com/twilio/oai/java/format/OpenApiSpecFormatFeatureConstants.java
- src/main/java/com/twilio/oai/java/format/Promoter.java
- src/main/java/com/twilio/oai/java/format/Promotion.java
added promotor and deserializer
The `Promoter` class is responsible for adding additional methods to provide flexibility
for customers to pass `String` as an input parameter instead of specific objects.
> Add format specific features
